SET search_path TO gitea, public;
/*Generated by xorm 2026-10-03 10:43:52, from sqlite3 to postgres*/

CREATE TABLE IF NOT EXISTS "gitea"."audit_event" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "action" VARCHAR(255) NOT NULL, "actor_id" BIGINT NOT NULL, "actor_name" VARCHAR(255) NULL, "actor_credential" VARCHAR(255) NULL, "impersonator_id" BIGINT NULL, "impersonator_name" VARCHAR(255) NULL, "scope_id" BIGINT NOT NULL, "scope_type" VARCHAR(255) NOT NULL, "scope_name" VARCHAR(255) NULL, "origin" VARCHAR(255) NOT NULL, "message" VARCHAR(255) NULL, "metadata" TEXT NULL, "ip_address" VARCHAR(255) NULL, "timestamp_unix" BIGINT NOT NULL); ;
CREATE INDEX "IDX_audit_event_origin" ON "audit_event" ("origin");
CREATE INDEX "IDX_audit_event_timestamp_unix" ON "audit_event" ("timestamp_unix");
CREATE INDEX "IDX_audit_event_action" ON "audit_event" ("action");
CREATE INDEX "IDX_audit_event_actor_id" ON "audit_event" ("actor_id");
CREATE INDEX "IDX_audit_event_impersonator_id" ON "audit_event" ("impersonator_id");
CREATE INDEX "IDX_audit_event_scope" ON "audit_event" ("scope_id","scope_type");
CREATE INDEX "IDX_audit_event_scope_type" ON "audit_event" ("scope_type");
SELECT setval('audit_event_id_seq', COALESCE((SELECT MAX(id) + 1 FROM "audit_event"), 1), false);

CREATE TABLE IF NOT EXISTS "gitea"."access_token" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "uid" BIGINT NULL, "name" VARCHAR(255) NULL, "token_hash" VARCHAR(255) NULL, "token_salt" VARCHAR(255) NULL, "token_last_eight" VARCHAR(255) NULL, "scope" VARCHAR(255) NULL, "created_unix" BIGINT NULL, "updated_unix" BIGINT NULL); ;
CREATE INDEX "IDX_access_token_uid" ON "access_token" ("uid");
CREATE UNIQUE INDEX "UQE_access_token_token_hash" ON "access_token" ("token_hash");
CREATE INDEX "IDX_access_token_token_last_eight" ON "access_token" ("token_last_eight");
CREATE INDEX "IDX_access_token_created_unix" ON "access_token" ("created_unix");
CREATE INDEX "IDX_access_token_updated_unix" ON "access_token" ("updated_unix");
SELECT setval('access_token_id_seq', COALESCE((SELECT MAX(id) + 1 FROM "access_token"), 1), false);

CREATE TABLE IF NOT EXISTS "gitea"."auth_token" ("id" VARCHAR(255) PRIMARY KEY NOT NULL, "token_hash" VARCHAR(255) NULL, "user_id" BIGINT NULL, "expires_unix" BIGINT NULL); ;
CREATE INDEX "IDX_auth_token_user_id" ON "auth_token" ("user_id");
CREATE INDEX "IDX_auth_token_expires_unix" ON "auth_token" ("expires_unix");

CREATE TABLE IF NOT EXISTS "gitea"."oauth2_application" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "uid" BIGINT NULL, "name" VARCHAR(255) NULL, "client_id" VARCHAR(255) NULL, "client_secret" VARCHAR(255) NULL, "confidential_client" BOOL DEFAULT TRUE NOT NULL, "skip_secondary_authorization" BOOL DEFAULT FALSE NOT NULL, "redirect_uris" TEXT NULL, "created_unix" BIGINT NULL, "updated_unix" BIGINT NULL); ;
CREATE INDEX "IDX_oauth2_application_uid" ON "oauth2_application" ("uid");
CREATE UNIQUE INDEX "UQE_oauth2_application_client_id" ON "oauth2_application" ("client_id");
CREATE INDEX "IDX_oauth2_application_created_unix" ON "oauth2_application" ("created_unix");
CREATE INDEX "IDX_oauth2_application_updated_unix" ON "oauth2_application" ("updated_unix");
INSERT INTO "oauth2_application" ("id", "uid", "name", "client_id", "client_secret", "confidential_client", "skip_secondary_authorization", "redirect_uris", "created_unix", "updated_unix") VALUES (1,0,'git-credential-oauth','a4792ccc-144e-407e-86c9-5e7d8d9c3269','',false,false,'["http://127.0.0.1","https://127.0.0.1"]',1791020950,1791020950);
INSERT INTO "oauth2_application" ("id", "uid", "name", "client_id", "client_secret", "confidential_client", "skip_secondary_authorization", "redirect_uris", "created_unix", "updated_unix") VALUES (2,0,'Git Credential Manager','e90ee53c-94e2-48ac-9358-a874fb9e0662','',false,false,'["http://127.0.0.1","https://127.0.0.1"]',1791020950,1791020950);
INSERT INTO "oauth2_application" ("id", "uid", "name", "client_id", "client_secret", "confidential_client", "skip_secondary_authorization", "redirect_uris", "created_unix", "updated_unix") VALUES (3,0,'tea','d57cb8c4-630c-4168-8324-ec79935e18d4','',false,false,'["http://127.0.0.1","https://127.0.0.1"]',1791020950,1791020950);
INSERT INTO "oauth2_application" ("id", "uid", "name", "client_id", "client_secret", "confidential_client", "skip_secondary_authorization", "redirect_uris", "created_unix", "updated_unix") VALUES (4,0,'Gitea App','b757811a-05c8-4c76-8d74-a5ee3d2073f2','',false,false,'["com.gitea.app://oauth/callback"]',1791020950,1791020950);
SELECT setval('oauth2_application_id_seq', COALESCE((SELECT MAX(id) + 1 FROM "oauth2_application"), 1), false);

CREATE TABLE IF NOT EXISTS "gitea"."oauth2_authorization_code" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "grant_id" BIGINT NULL, "code" VARCHAR(255) NULL, "code_challenge" VARCHAR(255) NULL, "code_challenge_method" VARCHAR(255) NULL, "redirect_uri" VARCHAR(255) NULL, "valid_until" BIGINT NULL); ;
CREATE UNIQUE INDEX "UQE_oauth2_authorization_code_code" ON "oauth2_authorization_code" ("code");
CREATE INDEX "IDX_oauth2_authorization_code_valid_until" ON "oauth2_authorization_code" ("valid_until");
SELECT setval('oauth2_authorization_code_id_seq', COALESCE((SELECT MAX(id) + 1 FROM "oauth2_authorization_code"), 1), false);

CREATE TABLE IF NOT EXISTS "gitea"."oauth2_grant" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "user_id" BIGINT NULL, "application_id" BIGINT NULL, "counter" BIGINT DEFAULT 1 NOT NULL, "scope" TEXT NULL, "nonce" TEXT NULL, "created_unix" BIGINT NULL, "updated_unix" BIGINT NULL); ;
CREATE UNIQUE INDEX "UQE_oauth2_grant_user_application" ON "oauth2_grant" ("user_id","application_id");
CREATE INDEX "IDX_oauth2_grant_user_id" ON "oauth2_grant" ("user_id");
CREATE INDEX "IDX_oauth2_grant_application_id" ON "oauth2_grant" ("application_id");
SELECT setval('oauth2_grant_id_seq', COALESCE((SELECT MAX(id) + 1 FROM "oauth2_grant"), 1), false);

CREATE TABLE IF NOT EXISTS "gitea"."session" ("key" CHAR(16) PRIMARY KEY NOT NULL, "data" BYTEA NULL, "expiry" BIGINT NULL); ;

CREATE TABLE IF NOT EXISTS "gitea"."login_source" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "type" INTEGER NULL, "name" VARCHAR(255) NULL, "is_active" BOOL DEFAULT false NOT NULL, "is_sync_enabled" BOOL DEFAULT false NOT NULL, "two_factor_policy" VARCHAR(255) DEFAULT '' NOT NULL, "cfg" TEXT NULL, "created_unix" BIGINT NULL, "updated_unix" BIGINT NULL); ;
CREATE INDEX "IDX_login_source_is_active" ON "login_source" ("is_active");
CREATE INDEX "IDX_login_source_is_sync_enabled" ON "login_source" ("is_sync_enabled");
CREATE INDEX "IDX_login_source_created_unix" ON "login_source" ("created_unix");
CREATE INDEX "IDX_login_source_updated_unix" ON "login_source" ("updated_unix");
CREATE UNIQUE INDEX "UQE_login_source_name" ON "login_source" ("name");
SELECT setval('login_source_id_seq', COALESCE((SELECT MAX(id) + 1 FROM "login_source"), 1), false);

CREATE TABLE IF NOT EXISTS "gitea"."two_factor" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "uid" BIGINT NULL, "secret" VARCHAR(255) NULL, "scratch_salt" VARCHAR(255) NULL, "scratch_hash" VARCHAR(255) NULL, "last_used_passcode" VARCHAR(10) NULL, "created_unix" BIGINT NULL, "updated_unix" BIGINT NULL); ;
CREATE UNIQUE INDEX "UQE_two_factor_uid" ON "two_factor" ("uid");
CREATE INDEX "IDX_two_factor_created_unix" ON "two_factor" ("created_unix");
CREATE INDEX "IDX_two_factor_updated_unix" ON "two_factor" ("updated_unix");
SELECT setval('two_factor_id_seq', COALESCE((SELECT MAX(id) + 1 FROM "two_factor"), 1), false);

CREATE TABLE IF NOT EXISTS "gitea"."webauthn_credential" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "name" VARCHAR(255) NULL, "lower_name" VARCHAR(255) NULL, "user_id" BIGINT NULL, "credential_id" BYTEA NULL, "public_key" BYTEA NULL, "attestation_type" VARCHAR(255) NULL, "aaguid" BYTEA NULL, "sign_count" BIGINT NULL, "clone_warning" BOOL NULL, "created_unix" BIGINT NULL, "updated_unix" BIGINT NULL); ;
CREATE UNIQUE INDEX "UQE_webauthn_credential_s" ON "webauthn_credential" ("lower_name","user_id");
CREATE INDEX "IDX_webauthn_credential_user_id" ON "webauthn_credential" ("user_id");
CREATE INDEX "IDX_webauthn_credential_credential_id" ON "webauthn_credential" ("credential_id");
CREATE INDEX "IDX_webauthn_credential_created_unix" ON "webauthn_credential" ("created_unix");
CREATE INDEX "IDX_webauthn_credential_updated_unix" ON "webauthn_credential" ("updated_unix");
SELECT setval('webauthn_credential_id_seq', COALESCE((SELECT MAX(id) + 1 FROM "webauthn_credential"), 1), false);

CREATE TABLE IF NOT EXISTS "gitea"."email_hash" ("hash" VARCHAR(64) PRIMARY KEY NOT NULL, "email" VARCHAR(255) NOT NULL, "hash_type" VARCHAR(16) NOT NULL); ;
CREATE UNIQUE INDEX "UQE_email_hash_email_hashtype" ON "email_hash" ("email","hash_type");

CREATE TABLE IF NOT EXISTS "gitea"."dbfs_meta" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "full_path" VARCHAR(500) NOT NULL, "block_size" BIGINT NOT NULL, "file_size" BIGINT NOT NULL, "create_timestamp" BIGINT NOT NULL, "modify_timestamp" BIGINT NOT NULL); ;
CREATE UNIQUE INDEX "UQE_dbfs_meta_full_path" ON "dbfs_meta" ("full_path");
SELECT setval('dbfs_meta_id_seq', COALESCE((SELECT MAX(id) + 1 FROM "dbfs_meta"), 1), false);

CREATE TABLE IF NOT EXISTS "gitea"."dbfs_data" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "revision" BIGINT NOT NULL, "meta_id" BIGINT NOT NULL, "blob_offset" BIGINT NOT NULL, "blob_size" BIGINT NOT NULL, "blob_data" BYTEA NOT NULL); ;
CREATE INDEX "IDX_dbfs_data_meta_offset" ON "dbfs_data" ("meta_id","blob_offset");
SELECT setval('dbfs_data_id_seq', COALESCE((SELECT MAX(id) + 1 FROM "dbfs_data"), 1), false);

CREATE TABLE IF NOT EXISTS "gitea"."app_state" ("id" VARCHAR(200) PRIMARY KEY NOT NULL, "revision" BIGINT NULL, "content" TEXT NULL); ;
INSERT INTO "app_state" ("id", "revision", "content") VALUES ('runtime-state',0,'{"last_app_path":"/home/ubuntu/gitea/bin/gitea","last_custom_conf":"/home/ubuntu/gitea/custom/conf/app.ini"}');

CREATE TABLE IF NOT EXISTS "gitea"."notice" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "type" INTEGER NULL, "description" TEXT NULL, "created_unix" BIGINT NULL); ;
CREATE INDEX "IDX_notice_created_unix" ON "notice" ("created_unix");
SELECT setval('notice_id_seq', COALESCE((SELECT MAX(id) + 1 FROM "notice"), 1), false);

CREATE TABLE IF NOT EXISTS "gitea"."system_setting" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "setting_key" VARCHAR(255) NULL, "setting_value" TEXT NULL, "version" INTEGER NULL, "created" BIGINT NULL, "updated" BIGINT NULL); ;
CREATE UNIQUE INDEX "UQE_system_setting_setting_key" ON "system_setting" ("setting_key");
INSERT INTO "system_setting" ("id", "setting_key", "setting_value", "version", "created", "updated") VALUES (1,'revision','',1,1791021018,1791021018);
SELECT setval('system_setting_id_seq', COALESCE((SELECT MAX(id) + 1 FROM "system_setting"), 1), false);

CREATE TABLE IF NOT EXISTS "gitea"."badge" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "slug" VARCHAR(255) NULL, "description" VARCHAR(255) NULL, "image_url" VARCHAR(255) NULL); ;
CREATE UNIQUE INDEX "UQE_badge_slug" ON "badge" ("slug");
SELECT setval('badge_id_seq', COALESCE((SELECT MAX(id) + 1 FROM "badge"), 1), false);

CREATE TABLE IF NOT EXISTS "gitea"."user_badge" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "badge_id" BIGINT NULL, "user_id" BIGINT NULL); ;
CREATE UNIQUE INDEX "UQE_user_badge_unique_user_badge" ON "user_badge" ("user_id","badge_id");
SELECT setval('user_badge_id_seq', COALESCE((SELECT MAX(id) + 1 FROM "user_badge"), 1), false);

CREATE TABLE IF NOT EXISTS "gitea"."user_blocking" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "blocker_id" BIGINT NULL, "blockee_id" BIGINT NULL, "note" VARCHAR(255) NULL, "created_unix" BIGINT NULL); ;
CREATE UNIQUE INDEX "UQE_user_blocking_block" ON "user_blocking" ("blocker_id","blockee_id");
CREATE INDEX "IDX_user_blocking_created_unix" ON "user_blocking" ("created_unix");
SELECT setval('user_blocking_id_seq', COALESCE((SELECT MAX(id) + 1 FROM "user_blocking"), 1), false);

CREATE TABLE IF NOT EXISTS "gitea"."email_address" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "uid" BIGINT NOT NULL, "email" VARCHAR(255) NOT NULL, "lower_email" VARCHAR(255) NOT NULL, "is_activated" BOOL NULL, "is_primary" BOOL DEFAULT false NOT NULL); ;
CREATE UNIQUE INDEX "UQE_email_address_email" ON "email_address" ("email");
CREATE UNIQUE INDEX "UQE_email_address_lower_email" ON "email_address" ("lower_email");
CREATE INDEX "IDX_email_address_uid" ON "email_address" ("uid");
INSERT INTO "email_address" ("id", "uid", "email", "lower_email", "is_activated", "is_primary") VALUES (1,1,'grykj249@gmail.com','grykj249@gmail.com',true,true);
SELECT setval('email_address_id_seq', COALESCE((SELECT MAX(id) + 1 FROM "email_address"), 1), false);

CREATE TABLE IF NOT EXISTS "gitea"."external_login_user" ("external_id" VARCHAR(255) NOT NULL, "user_id" BIGINT NOT NULL, "login_source_id" BIGINT NOT NULL, "raw_data" TEXT NULL, "provider" VARCHAR(25) NULL, "email" VARCHAR(255) NULL, "name" VARCHAR(255) NULL, "first_name" VARCHAR(255) NULL, "last_name" VARCHAR(255) NULL, "nick_name" VARCHAR(255) NULL, "description" VARCHAR(255) NULL, "avatar_url" TEXT NULL, "location" VARCHAR(255) NULL, "access_token" TEXT NULL, "access_token_secret" TEXT NULL, "refresh_token" TEXT NULL, "expires_at" TIMESTAMP NULL, PRIMARY KEY ("external_id","login_source_id")); ;
CREATE INDEX "IDX_external_login_user_user_id" ON "external_login_user" ("user_id");
CREATE INDEX "IDX_external_login_user_provider" ON "external_login_user" ("provider");

CREATE TABLE IF NOT EXISTS "gitea"."follow" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "user_id" BIGINT NULL, "follow_id" BIGINT NULL, "created_unix" BIGINT NULL); ;
CREATE UNIQUE INDEX "UQE_follow_follow" ON "follow" ("user_id","follow_id");
CREATE INDEX "IDX_follow_created_unix" ON "follow" ("created_unix");
SELECT setval('follow_id_seq', COALESCE((SELECT MAX(id) + 1 FROM "follow"), 1), false);

CREATE TABLE IF NOT EXISTS "gitea"."user_open_id" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "uid" BIGINT NOT NULL, "uri" VARCHAR(255) NOT NULL, "show" BOOL DEFAULT false NULL); ;
CREATE INDEX "IDX_user_open_id_uid" ON "user_open_id" ("uid");
CREATE UNIQUE INDEX "UQE_user_open_id_uri" ON "user_open_id" ("uri");
SELECT setval('user_open_id_id_seq', COALESCE((SELECT MAX(id) + 1 FROM "user_open_id"), 1), false);

CREATE TABLE IF NOT EXISTS "gitea"."user_redirect" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "lower_name" VARCHAR(255) NOT NULL, "redirect_user_id" BIGINT NULL); ;
CREATE INDEX "IDX_user_redirect_lower_name" ON "user_redirect" ("lower_name");
CREATE UNIQUE INDEX "UQE_user_redirect_s" ON "user_redirect" ("lower_name");
SELECT setval('user_redirect_id_seq', COALESCE((SELECT MAX(id) + 1 FROM "user_redirect"), 1), false);

CREATE TABLE IF NOT EXISTS "gitea"."user_setting" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "user_id" BIGINT NULL, "setting_key" VARCHAR(255) NULL, "setting_value" TEXT NULL); ;
CREATE INDEX "IDX_user_setting_setting_key" ON "user_setting" ("setting_key");
CREATE UNIQUE INDEX "UQE_user_setting_key_userid" ON "user_setting" ("user_id","setting_key");
CREATE INDEX "IDX_user_setting_user_id" ON "user_setting" ("user_id");
SELECT setval('user_setting_id_seq', COALESCE((SELECT MAX(id) + 1 FROM "user_setting"), 1), false);

CREATE TABLE IF NOT EXISTS "gitea"."user" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "lower_name" VARCHAR(255) NOT NULL, "name" VARCHAR(255) NOT NULL, "full_name" VARCHAR(255) NULL, "email" VARCHAR(255) NOT NULL, "keep_email_private" BOOL NULL, "email_notifications_preference" VARCHAR(20) DEFAULT 'enabled' NOT NULL, "passwd" VARCHAR(255) NOT NULL, "passwd_hash_algo" VARCHAR(255) DEFAULT 'argon2' NOT NULL, "must_change_password" BOOL DEFAULT false NOT NULL, "login_type" INTEGER NULL, "login_source" BIGINT DEFAULT 0 NOT NULL, "login_name" VARCHAR(255) NULL, "type" INTEGER NULL, "location" VARCHAR(255) NULL, "website" VARCHAR(255) NULL, "rands" VARCHAR(32) NULL, "salt" VARCHAR(32) NULL, "language" VARCHAR(5) NULL, "description" VARCHAR(255) NULL, "created_unix" BIGINT NULL, "updated_unix" BIGINT NULL, "last_login_unix" BIGINT NULL, "last_repo_visibility" BOOL NULL, "max_repo_creation" INTEGER DEFAULT -1 NOT NULL, "is_active" BOOL NULL, "is_admin" BOOL NULL, "is_restricted" BOOL DEFAULT false NOT NULL, "allow_git_hook" BOOL NULL, "allow_import_local" BOOL NULL, "allow_create_organization" BOOL DEFAULT true NULL, "prohibit_login" BOOL DEFAULT false NOT NULL, "avatar" VARCHAR(2048) NOT NULL, "avatar_email" VARCHAR(255) NOT NULL, "use_custom_avatar" BOOL NULL, "num_followers" INTEGER NULL, "num_following" INTEGER DEFAULT 0 NOT NULL, "num_stars" INTEGER NULL, "num_repos" INTEGER NULL, "num_teams" INTEGER NULL, "num_members" INTEGER NULL, "visibility" INTEGER DEFAULT 0 NOT NULL, "repo_admin_change_team_access" BOOL DEFAULT false NOT NULL, "diff_view_style" VARCHAR(255) DEFAULT '' NOT NULL, "theme" VARCHAR(255) DEFAULT '' NOT NULL, "keep_activity_private" BOOL DEFAULT false NOT NULL); ;
CREATE INDEX "IDX_user_updated_unix" ON "user" ("updated_unix");
CREATE INDEX "IDX_user_last_login_unix" ON "user" ("last_login_unix");
CREATE INDEX "IDX_user_is_active" ON "user" ("is_active");
CREATE UNIQUE INDEX "UQE_user_lower_name" ON "user" ("lower_name");
CREATE UNIQUE INDEX "UQE_user_name" ON "user" ("name");
CREATE INDEX "IDX_user_created_unix" ON "user" ("created_unix");
INSERT INTO "user" ("id", "lower_name", "name", "full_name", "email", "keep_email_private", "email_notifications_preference", "passwd", "passwd_hash_algo", "must_change_password", "login_type", "login_source", "login_name", "type", "location", "website", "rands", "salt", "language", "description", "created_unix", "updated_unix", "last_login_unix", "last_repo_visibility", "max_repo_creation", "is_active", "is_admin", "is_restricted", "allow_git_hook", "allow_import_local", "allow_create_organization", "prohibit_login", "avatar", "avatar_email", "use_custom_avatar", "num_followers", "num_following", "num_stars", "num_repos", "num_teams", "num_members", "visibility", "repo_admin_change_team_access", "diff_view_style", "theme", "keep_activity_private") VALUES (1,'opera-1','opera-1','Opera Admin','grykj249@gmail.com',false,'enabled','','',false,0,0,'',0,'','','0506a28903fe99d339b9c2dcaeaf46f6','','en-US','',1791021018,1791023909,1791023909,false,-1,true,false,false,false,false,true,false,'02689abd25110e500e166bd5b2507dad9421b8147956c8e157819cad93510638','grykj249@gmail.com',false,0,0,0,0,0,0,0,false,'','gitea-auto',false);
SELECT setval('user_id_seq', COALESCE((SELECT MAX(id) + 1 FROM "user"), 1), false);

CREATE TABLE IF NOT EXISTS "gitea"."org_user" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "uid" BIGINT NULL, "org_id" BIGINT NULL, "is_public" BOOL NULL); ;
CREATE INDEX "IDX_org_user_org_id" ON "org_user" ("org_id");
CREATE INDEX "IDX_org_user_is_public" ON "org_user" ("is_public");
CREATE UNIQUE INDEX "UQE_org_user_s" ON "org_user" ("uid","org_id");
CREATE INDEX "IDX_org_user_uid" ON "org_user" ("uid");
SELECT setval('org_user_id_seq', COALESCE((SELECT MAX(id) + 1 FROM "org_user"), 1), false);

CREATE TABLE IF NOT EXISTS "gitea"."team" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "org_id" BIGINT NULL, "lower_name" VARCHAR(255) NULL, "name" VARCHAR(255) NULL, "description" VARCHAR(255) NULL, "authorize" INTEGER NULL, "num_repos" INTEGER NULL, "num_members" INTEGER NULL, "includes_all_repositories" BOOL DEFAULT false NOT NULL, "can_create_org_repo" BOOL DEFAULT false NOT NULL, "visibility" INTEGER DEFAULT 2 NOT NULL); ;
CREATE INDEX "IDX_team_org_id" ON "team" ("org_id");
SELECT setval('team_id_seq', COALESCE((SELECT MAX(id) + 1 FROM "team"), 1), false);

CREATE TABLE IF NOT EXISTS "gitea"."team_user" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "org_id" BIGINT NULL, "team_id" BIGINT NULL, "uid" BIGINT NULL); ;
CREATE UNIQUE INDEX "UQE_team_user_s" ON "team_user" ("team_id","uid");
CREATE INDEX "IDX_team_user_org_id" ON "team_user" ("org_id");
SELECT setval('team_user_id_seq', COALESCE((SELECT MAX(id) + 1 FROM "team_user"), 1), false);

CREATE TABLE IF NOT EXISTS "gitea"."team_repo" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "org_id" BIGINT NULL, "team_id" BIGINT NULL, "repo_id" BIGINT NULL); ;
CREATE INDEX "IDX_team_repo_org_id" ON "team_repo" ("org_id");
CREATE UNIQUE INDEX "UQE_team_repo_s" ON "team_repo" ("team_id","repo_id");
SELECT setval('team_repo_id_seq', COALESCE((SELECT MAX(id) + 1 FROM "team_repo"), 1), false);

CREATE TABLE IF NOT EXISTS "gitea"."team_unit" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "org_id" BIGINT NULL, "team_id" BIGINT NULL, "type" INTEGER NULL, "access_mode" INTEGER NULL); ;
CREATE UNIQUE INDEX "UQE_team_unit_s" ON "team_unit" ("team_id","type");
CREATE INDEX "IDX_team_unit_org_id" ON "team_unit" ("org_id");
SELECT setval('team_unit_id_seq', COALESCE((SELECT MAX(id) + 1 FROM "team_unit"), 1), false);

CREATE TABLE IF NOT EXISTS "gitea"."team_invite" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "token" VARCHAR(255) DEFAULT '' NOT NULL, "inviter_id" BIGINT DEFAULT 0 NOT NULL, "org_id" BIGINT DEFAULT 0 NOT NULL, "team_id" BIGINT DEFAULT 0 NOT NULL, "email" VARCHAR(255) DEFAULT '' NOT NULL, "created_unix" BIGINT NULL, "updated_unix" BIGINT NULL); ;
CREATE UNIQUE INDEX "UQE_team_invite_team_mail" ON "team_invite" ("team_id","email");
CREATE INDEX "IDX_team_invite_team_id" ON "team_invite" ("team_id");
CREATE INDEX "IDX_team_invite_created_unix" ON "team_invite" ("created_unix");
CREATE INDEX "IDX_team_invite_updated_unix" ON "team_invite" ("updated_unix");
CREATE INDEX "IDX_team_invite_token" ON "team_invite" ("token");
CREATE INDEX "IDX_team_invite_org_id" ON "team_invite" ("org_id");
SELECT setval('team_invite_id_seq', COALESCE((SELECT MAX(id) + 1 FROM "team_invite"), 1), false);

CREATE TABLE IF NOT EXISTS "gitea"."repo_archiver" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "repo_id" BIGINT NULL, "type" INTEGER NULL, "status" INTEGER NULL, "commit_id" VARCHAR(64) NULL, "created_unix" BIGINT NOT NULL); ;
CREATE INDEX "IDX_repo_archiver_repo_id" ON "repo_archiver" ("repo_id");
CREATE INDEX "IDX_repo_archiver_created_unix" ON "repo_archiver" ("created_unix");
CREATE UNIQUE INDEX "UQE_repo_archiver_s" ON "repo_archiver" ("repo_id","type","commit_id");
SELECT setval('repo_archiver_id_seq', COALESCE((SELECT MAX(id) + 1 FROM "repo_archiver"), 1), false);

CREATE TABLE IF NOT EXISTS "gitea"."attachment" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "uuid" UUID NULL, "repo_id" BIGINT NULL, "issue_id" BIGINT NULL, "release_id" BIGINT NULL, "uploader_id" BIGINT DEFAULT 0 NULL, "comment_id" BIGINT NULL, "name" VARCHAR(255) NULL, "download_count" BIGINT DEFAULT 0 NULL, "size" BIGINT DEFAULT 0 NULL, "created_unix" BIGINT NULL); ;
CREATE UNIQUE INDEX "UQE_attachment_uuid" ON "attachment" ("uuid");
CREATE INDEX "IDX_attachment_repo_id" ON "attachment" ("repo_id");
CREATE INDEX "IDX_attachment_issue_id" ON "attachment" ("issue_id");
CREATE INDEX "IDX_attachment_release_id" ON "attachment" ("release_id");
CREATE INDEX "IDX_attachment_uploader_id" ON "attachment" ("uploader_id");
CREATE INDEX "IDX_attachment_comment_id" ON "attachment" ("comment_id");
SELECT setval('attachment_id_seq', COALESCE((SELECT MAX(id) + 1 FROM "attachment"), 1), false);

CREATE TABLE IF NOT EXISTS "gitea"."collaboration" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "repo_id" BIGINT NOT NULL, "user_id" BIGINT NOT NULL, "mode" INTEGER DEFAULT 2 NOT NULL, "created_unix" BIGINT NULL, "updated_unix" BIGINT NULL); ;
CREATE INDEX "IDX_collaboration_repo_id" ON "collaboration" ("repo_id");
CREATE INDEX "IDX_collaboration_user_id" ON "collaboration" ("user_id");
CREATE INDEX "IDX_collaboration_created_unix" ON "collaboration" ("created_unix");
CREATE INDEX "IDX_collaboration_updated_unix" ON "collaboration" ("updated_unix");
CREATE UNIQUE INDEX "UQE_collaboration_s" ON "collaboration" ("repo_id","user_id");
SELECT setval('collaboration_id_seq', COALESCE((SELECT MAX(id) + 1 FROM "collaboration"), 1), false);

CREATE TABLE IF NOT EXISTS "gitea"."language_stat" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "repo_id" BIGINT NOT NULL, "commit_id" VARCHAR(255) NULL, "is_primary" BOOL NULL, "language" VARCHAR(50) NOT NULL, "size" BIGINT DEFAULT 0 NOT NULL, "created_unix" BIGINT NULL); ;
CREATE UNIQUE INDEX "UQE_language_stat_s" ON "language_stat" ("repo_id","language");
CREATE INDEX "IDX_language_stat_repo_id" ON "language_stat" ("repo_id");
CREATE INDEX "IDX_language_stat_language" ON "language_stat" ("language");
CREATE INDEX "IDX_language_stat_created_unix" ON "language_stat" ("created_unix");
SELECT setval('language_stat_id_seq', COALESCE((SELECT MAX(id) + 1 FROM "language_stat"), 1), false);

CREATE TABLE IF NOT EXISTS "gitea"."repo_license" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "repo_id" BIGINT NOT NULL, "commit_id" VARCHAR(255) NULL, "license" VARCHAR(255) NOT NULL, "license_path" VARCHAR(255) DEFAULT 'LICENSE' NOT NULL, "created_unix" BIGINT NULL, "updated_unix" BIGINT NULL); ;
CREATE UNIQUE INDEX "UQE_repo_license_path" ON "repo_license" ("repo_id","license","license_path");
CREATE INDEX "IDX_repo_license_created_unix" ON "repo_license" ("created_unix");
CREATE INDEX "IDX_repo_license_updated_unix" ON "repo_license" ("updated_unix");
SELECT setval('repo_license_id_seq', COALESCE((SELECT MAX(id) + 1 FROM "repo_license"), 1), false);

CREATE TABLE IF NOT EXISTS "gitea"."mirror" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "repo_id" BIGINT NULL, "interval" BIGINT NULL, "enable_prune" BOOL DEFAULT true NOT NULL, "updated_unix" BIGINT NULL, "next_update_unix" BIGINT NULL, "last_sync_unix" BIGINT NULL, "lfs_enabled" BOOL DEFAULT false NOT NULL, "lfs_endpoint" TEXT NULL, "remote_address" VARCHAR(2048) NULL); ;
CREATE INDEX "IDX_mirror_updated_unix" ON "mirror" ("updated_unix");
CREATE INDEX "IDX_mirror_next_update_unix" ON "mirror" ("next_update_unix");
CREATE INDEX "IDX_mirror_last_sync_unix" ON "mirror" ("last_sync_unix");
CREATE INDEX "IDX_mirror_repo_id" ON "mirror" ("repo_id");
SELECT setval('mirror_id_seq', COALESCE((SELECT MAX(id) + 1 FROM "mirror"), 1), false);

CREATE TABLE IF NOT EXISTS "gitea"."push_mirror" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "repo_id" BIGINT NULL, "remote_name" VARCHAR(255) NULL, "remote_address" VARCHAR(2048) NULL, "sync_on_commit" BOOL DEFAULT true NOT NULL, "interval" BIGINT NULL, "created_unix" BIGINT NULL, "last_update" BIGINT NULL, "last_error" TEXT NULL); ;
CREATE INDEX "IDX_push_mirror_last_update" ON "push_mirror" ("last_update");
CREATE INDEX "IDX_push_mirror_repo_id" ON "push_mirror" ("repo_id");
SELECT setval('push_mirror_id_seq', COALESCE((SELECT MAX(id) + 1 FROM "push_mirror"), 1), false);

CREATE TABLE IF NOT EXISTS "gitea"."repo_redirect" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "owner_id" BIGINT NULL, "lower_name" VARCHAR(255) NOT NULL, "redirect_repo_id" BIGINT NULL); ;
CREATE INDEX "IDX_repo_redirect_lower_name" ON "repo_redirect" ("lower_name");
CREATE UNIQUE INDEX "UQE_repo_redirect_s" ON "repo_redirect" ("owner_id","lower_name");
SELECT setval('repo_redirect_id_seq', COALESCE((SELECT MAX(id) + 1 FROM "repo_redirect"), 1), false);

CREATE TABLE IF NOT EXISTS "gitea"."release" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "repo_id" BIGINT NULL, "publisher_id" BIGINT NULL, "tag_name" VARCHAR(255) NULL, "original_author" VARCHAR(255) NULL, "original_author_id" BIGINT NULL, "lower_tag_name" VARCHAR(255) NULL, "target" VARCHAR(255) NULL, "title" VARCHAR(255) NULL, "sha1" VARCHAR(64) NULL, "num_commits" BIGINT NULL, "note" TEXT NULL, "is_draft" BOOL DEFAULT false NOT NULL, "is_prerelease" BOOL DEFAULT false NOT NULL, "is_tag" BOOL DEFAULT false NOT NULL, "created_unix" BIGINT NULL, "published_unix" BIGINT DEFAULT 0 NOT NULL); ;
CREATE INDEX "IDX_release_original_author_id" ON "release" ("original_author_id");
CREATE INDEX "IDX_release_sha1" ON "release" ("sha1");
CREATE INDEX "IDX_release_created_unix" ON "release" ("created_unix");
CREATE UNIQUE INDEX "UQE_release_n" ON "release" ("repo_id","tag_name");
CREATE INDEX "IDX_release_repo_id" ON "release" ("repo_id");
CREATE INDEX "IDX_release_publisher_id" ON "release" ("publisher_id");
CREATE INDEX "IDX_release_tag_name" ON "release" ("tag_name");
SELECT setval('release_id_seq', COALESCE((SELECT MAX(id) + 1 FROM "release"), 1), false);

CREATE TABLE IF NOT EXISTS "gitea"."repository" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "owner_id" BIGINT NULL, "owner_name" VARCHAR(255) NULL, "lower_name" VARCHAR(255) NOT NULL, "name" VARCHAR(255) NOT NULL, "description" TEXT NULL, "website" VARCHAR(2048) NULL, "original_service_type" INTEGER NULL, "original_url" VARCHAR(2048) NULL, "default_branch" VARCHAR(255) NULL, "default_wiki_branch" VARCHAR(255) NULL, "num_watches" INTEGER NULL, "num_stars" INTEGER NULL, "num_forks" INTEGER NULL, "num_issues" INTEGER NULL, "num_closed_issues" INTEGER NULL, "num_pulls" INTEGER NULL, "num_closed_pulls" INTEGER NULL, "num_milestones" INTEGER DEFAULT 0 NOT NULL, "num_closed_milestones" INTEGER DEFAULT 0 NOT NULL, "num_projects" INTEGER DEFAULT 0 NOT NULL, "num_closed_projects" INTEGER DEFAULT 0 NOT NULL, "num_action_runs" INTEGER DEFAULT 0 NOT NULL, "num_closed_action_runs" INTEGER DEFAULT 0 NOT NULL, "is_private" BOOL NULL, "is_empty" BOOL NULL, "is_archived" BOOL NULL, "is_mirror" BOOL NULL, "status" INTEGER DEFAULT 0 NOT NULL, "is_fork" BOOL DEFAULT false NOT NULL, "fork_id" BIGINT NULL, "is_template" BOOL DEFAULT false NOT NULL, "template_id" BIGINT NULL, "size" BIGINT DEFAULT 0 NOT NULL, "git_size" BIGINT DEFAULT 0 NOT NULL, "lfs_size" BIGINT DEFAULT 0 NOT NULL, "is_fsck_enabled" BOOL DEFAULT true NOT NULL, "close_issues_via_commit_in_any_branch" BOOL DEFAULT false NOT NULL, "topics" TEXT NULL, "object_format_name" VARCHAR(6) DEFAULT 'sha1' NOT NULL, "trust_model" INTEGER NULL, "avatar" VARCHAR(64) NULL, "created_unix" BIGINT NULL, "updated_unix" BIGINT NULL, "archived_unix" BIGINT DEFAULT 0 NULL); ;
CREATE INDEX "IDX_repository_lower_name" ON "repository" ("lower_name");
CREATE INDEX "IDX_repository_original_service_type" ON "repository" ("original_service_type");
CREATE INDEX "IDX_repository_is_empty" ON "repository" ("is_empty");
CREATE INDEX "IDX_repository_is_mirror" ON "repository" ("is_mirror");
CREATE INDEX "IDX_repository_is_template" ON "repository" ("is_template");
CREATE UNIQUE INDEX "UQE_repository_s" ON "repository" ("owner_id","lower_name");
CREATE INDEX "IDX_repository_is_fork" ON "repository" ("is_fork");
CREATE INDEX "IDX_repository_template_id" ON "repository" ("template_id");
CREATE INDEX "IDX_repository_name" ON "repository" ("name");
CREATE INDEX "IDX_repository_is_private" ON "repository" ("is_private");
CREATE INDEX "IDX_repository_is_archived" ON "repository" ("is_archived");
CREATE INDEX "IDX_repository_fork_id" ON "repository" ("fork_id");
CREATE INDEX "IDX_repository_created_unix" ON "repository" ("created_unix");
CREATE INDEX "IDX_repository_owner_id" ON "repository" ("owner_id");
CREATE INDEX "IDX_repository_updated_unix" ON "repository" ("updated_unix");
SELECT setval('repository_id_seq', COALESCE((SELECT MAX(id) + 1 FROM "repository"), 1), false);

CREATE TABLE IF NOT EXISTS "gitea"."repo_indexer_status" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "repo_id" BIGINT NULL, "commit_sha" VARCHAR(64) NULL, "indexer_type" INTEGER DEFAULT 0 NOT NULL); ;
CREATE INDEX "IDX_repo_indexer_status_s" ON "repo_indexer_status" ("repo_id","indexer_type");
SELECT setval('repo_indexer_status_id_seq', COALESCE((SELECT MAX(id) + 1 FROM "repo_indexer_status"), 1), false);

CREATE TABLE IF NOT EXISTS "gitea"."repo_unit" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "repo_id" BIGINT NULL, "type" INTEGER NULL, "config" TEXT NULL, "created_unix" BIGINT NULL, "anonymous_access_mode" INTEGER DEFAULT 0 NOT NULL, "everyone_access_mode" INTEGER DEFAULT 0 NOT NULL); ;
CREATE INDEX "IDX_repo_unit_s" ON "repo_unit" ("repo_id","type");
CREATE INDEX "IDX_repo_unit_created_unix" ON "repo_unit" ("created_unix");
SELECT setval('repo_unit_id_seq', COALESCE((SELECT MAX(id) + 1 FROM "repo_unit"), 1), false);

CREATE TABLE IF NOT EXISTS "gitea"."star" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "uid" BIGINT NULL, "repo_id" BIGINT NULL, "created_unix" BIGINT NULL); ;
CREATE UNIQUE INDEX "UQE_star_s" ON "star" ("uid","repo_id");
CREATE INDEX "IDX_star_created_unix" ON "star" ("created_unix");
SELECT setval('star_id_seq', COALESCE((SELECT MAX(id) + 1 FROM "star"), 1), false);

CREATE TABLE IF NOT EXISTS "gitea"."topic" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "name" VARCHAR(50) NULL, "repo_count" INTEGER NULL, "created_unix" BIGINT NULL, "updated_unix" BIGINT NULL); ;
CREATE INDEX "IDX_topic_updated_unix" ON "topic" ("updated_unix");
CREATE UNIQUE INDEX "UQE_topic_name" ON "topic" ("name");
CREATE INDEX "IDX_topic_created_unix" ON "topic" ("created_unix");
SELECT setval('topic_id_seq', COALESCE((SELECT MAX(id) + 1 FROM "topic"), 1), false);

CREATE TABLE IF NOT EXISTS "gitea"."repo_topic" ("repo_id" BIGINT NOT NULL, "topic_id" BIGINT NOT NULL, PRIMARY KEY ("repo_id","topic_id")); ;

CREATE TABLE IF NOT EXISTS "gitea"."repo_transfer" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "doer_id" BIGINT NULL, "recipient_id" BIGINT NULL, "repo_id" BIGINT NULL, "team_i_ds" TEXT NULL, "recipient_access_granted" BOOL DEFAULT false NOT NULL, "created_unix" BIGINT NOT NULL, "updated_unix" BIGINT NOT NULL); ;
CREATE INDEX "IDX_repo_transfer_updated_unix" ON "repo_transfer" ("updated_unix");
CREATE INDEX "IDX_repo_transfer_created_unix" ON "repo_transfer" ("created_unix");
SELECT setval('repo_transfer_id_seq', COALESCE((SELECT MAX(id) + 1 FROM "repo_transfer"), 1), false);

CREATE TABLE IF NOT EXISTS "gitea"."upload" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "uuid" UUID NULL, "name" VARCHAR(255) NULL); ;
CREATE UNIQUE INDEX "UQE_upload_uuid" ON "upload" ("uuid");
SELECT setval('upload_id_seq', COALESCE((SELECT MAX(id) + 1 FROM "upload"), 1), false);

CREATE TABLE IF NOT EXISTS "gitea"."watch" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "user_id" BIGINT NULL, "repo_id" BIGINT NULL, "mode" SMALLINT DEFAULT 1 NOT NULL, "created_unix" BIGINT NULL, "updated_unix" BIGINT NULL, "include_pull_requests" BOOL DEFAULT true NOT NULL, "include_issues" BOOL DEFAULT true NOT NULL, "include_releases" BOOL DEFAULT true NOT NULL); ;
CREATE UNIQUE INDEX "UQE_watch_watch" ON "watch" ("user_id","repo_id");
CREATE INDEX "IDX_watch_created_unix" ON "watch" ("created_unix");
CREATE INDEX "IDX_watch_updated_unix" ON "watch" ("updated_unix");
SELECT setval('watch_id_seq', COALESCE((SELECT MAX(id) + 1 FROM "watch"), 1), false);

CREATE TABLE IF NOT EXISTS "gitea"."action_artifact" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "run_id" BIGINT NULL, "run_attempt_id" BIGINT DEFAULT 0 NOT NULL, "runner_id" BIGINT NULL, "repo_id" BIGINT NULL, "owner_id" BIGINT NULL, "commit_sha" VARCHAR(255) NULL, "storage_path" VARCHAR(255) NULL, "file_size" BIGINT NULL, "file_compressed_size" BIGINT NULL, "content_encoding" VARCHAR(255) NULL, "artifact_path" VARCHAR(255) NULL, "artifact_name" VARCHAR(255) NULL, "status" BIGINT NULL, "created_unix" BIGINT NULL, "updated_unix" BIGINT NULL, "expired_unix" BIGINT NULL); ;
CREATE UNIQUE INDEX "UQE_action_artifact_runid_attempt_name_path" ON "action_artifact" ("run_id","run_attempt_id","artifact_path","artifact_name");
CREATE INDEX "IDX_action_artifact_run_id" ON "action_artifact" ("run_id");
CREATE INDEX "IDX_action_artifact_repo_id" ON "action_artifact" ("repo_id");
CREATE INDEX "IDX_action_artifact_artifact_path" ON "action_artifact" ("artifact_path");
CREATE INDEX "IDX_action_artifact_artifact_name" ON "action_artifact" ("artifact_name");
CREATE INDEX "IDX_action_artifact_expired_unix" ON "action_artifact" ("expired_unix");
CREATE INDEX "IDX_action_artifact_run_attempt_id" ON "action_artifact" ("run_attempt_id");
CREATE INDEX "IDX_action_artifact_status" ON "action_artifact" ("status");
CREATE INDEX "IDX_action_artifact_updated_unix" ON "action_artifact" ("updated_unix");
SELECT setval('action_artifact_id_seq', COALESCE((SELECT MAX(id) + 1 FROM "action_artifact"), 1), false);

CREATE TABLE IF NOT EXISTS "gitea"."action_run" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "title" VARCHAR(255) NULL, "repo_id" BIGINT NULL, "owner_id" BIGINT NULL, "workflow_id" VARCHAR(255) NULL, "index" BIGINT NULL, "trigger_user_id" BIGINT NULL, "schedule_id" BIGINT NULL, "ref" VARCHAR(255) NULL, "commit_sha" VARCHAR(255) NULL, "is_fork_pull_request" BOOL NULL, "need_approval" BOOL NULL, "approved_by" BIGINT NULL, "event" VARCHAR(255) NULL, "event_payload" TEXT NULL, "trigger_event" VARCHAR(255) NULL, "status" INTEGER NULL, "version" INTEGER DEFAULT 0 NULL, "raw_concurrency" VARCHAR(255) NULL, "workflow_repo_id" BIGINT DEFAULT 0 NOT NULL, "workflow_commit_sha" VARCHAR(64) DEFAULT '' NOT NULL, "is_scoped_run" BOOL DEFAULT false NOT NULL, "started" BIGINT NULL, "stopped" BIGINT NULL, "previous_duration" BIGINT NULL, "latest_attempt_id" BIGINT DEFAULT 0 NOT NULL, "created" BIGINT NULL, "updated" BIGINT NULL); ;
CREATE INDEX "IDX_action_run_approved_by" ON "action_run" ("approved_by");
CREATE INDEX "IDX_action_run_status" ON "action_run" ("status");
CREATE UNIQUE INDEX "UQE_action_run_repo_index" ON "action_run" ("repo_id","index");
CREATE INDEX "IDX_action_run_owner_id" ON "action_run" ("owner_id");
CREATE INDEX "IDX_action_run_workflow_id" ON "action_run" ("workflow_id");
CREATE INDEX "IDX_action_run_ref" ON "action_run" ("ref");
CREATE INDEX "IDX_action_run_latest_attempt_id" ON "action_run" ("latest_attempt_id");
CREATE INDEX "IDX_action_run_repo_status" ON "action_run" ("repo_id","status");
CREATE INDEX "IDX_action_run_index" ON "action_run" ("index");
CREATE INDEX "IDX_action_run_trigger_user_id" ON "action_run" ("trigger_user_id");
SELECT setval('action_run_id_seq', COALESCE((SELECT MAX(id) + 1 FROM "action_run"), 1), false);

CREATE TABLE IF NOT EXISTS "gitea"."action_run_index" ("group_id" BIGINT PRIMARY KEY NOT NULL, "max_index" BIGINT NULL); ;
CREATE INDEX "IDX_action_run_index_max_index" ON "action_run_index" ("max_index");

CREATE TABLE IF NOT EXISTS "gitea"."action_run_attempt" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "repo_id" BIGINT NULL, "run_id" BIGINT NULL, "attempt" BIGINT NULL, "trigger_user_id" BIGINT NULL, "concurrency_group" VARCHAR(255) DEFAULT '' NOT NULL, "concurrency_cancel" BOOL DEFAULT FALSE NOT NULL, "status" INTEGER NULL, "started" BIGINT NULL, "stopped" BIGINT NULL, "created" BIGINT NULL, "updated" BIGINT NULL); ;
CREATE INDEX "IDX_action_run_attempt_repo_concurrency_status" ON "action_run_attempt" ("repo_id","concurrency_group","status");
CREATE UNIQUE INDEX "UQE_action_run_attempt_run_attempt" ON "action_run_attempt" ("run_id","attempt");
SELECT setval('action_run_attempt_id_seq', COALESCE((SELECT MAX(id) + 1 FROM "action_run_attempt"), 1), false);

CREATE TABLE IF NOT EXISTS "gitea"."action_run_job" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "run_id" BIGINT NULL, "repo_id" BIGINT NULL, "owner_id" BIGINT NULL, "commit_sha" VARCHAR(255) NULL, "is_fork_pull_request" BOOL NULL, "name" VARCHAR(255) NULL, "attempt" BIGINT NULL, "workflow_payload" BYTEA NULL, "job_id" VARCHAR(255) NULL, "needs" TEXT NULL, "runs_on" TEXT NULL, "task_id" BIGINT NULL, "source_task_id" BIGINT DEFAULT 0 NOT NULL, "status" INTEGER NULL, "raw_concurrency" VARCHAR(255) NULL, "is_concurrency_evaluated" BOOL NULL, "concurrency_group" VARCHAR(255) DEFAULT '' NOT NULL, "concurrency_cancel" BOOL DEFAULT FALSE NOT NULL, "token_permissions" TEXT NULL, "max_parallel" INTEGER DEFAULT 0 NOT NULL, "is_matrix_deferred" BOOL DEFAULT FALSE NOT NULL, "deferred_matrix_payload" BYTEA NULL, "run_attempt_id" BIGINT DEFAULT 0 NOT NULL, "attempt_job_id" BIGINT DEFAULT 0 NOT NULL, "workflow_source_repo_id" BIGINT DEFAULT 0 NOT NULL, "workflow_source_commit_sha" VARCHAR(64) DEFAULT '' NOT NULL, "is_reusable_caller" BOOL DEFAULT FALSE NOT NULL, "is_expanded" BOOL DEFAULT FALSE NOT NULL, "call_uses" VARCHAR(512) DEFAULT '' NOT NULL, "reusable_workflow_content" BYTEA NULL, "call_secrets" TEXT NULL, "call_payload" TEXT NULL, "parent_job_id" BIGINT DEFAULT 0 NOT NULL, "continue_on_error" BOOL DEFAULT FALSE NOT NULL, "started" BIGINT NULL, "stopped" BIGINT NULL, "created" BIGINT NULL, "updated" BIGINT NULL); ;
CREATE INDEX "IDX_action_run_job_parent_job_id" ON "action_run_job" ("parent_job_id");
CREATE INDEX "IDX_action_run_job_updated" ON "action_run_job" ("updated");
CREATE INDEX "IDX_action_run_job_repo_concurrency" ON "action_run_job" ("repo_id","concurrency_group");
CREATE INDEX "IDX_action_run_job_commit_sha" ON "action_run_job" ("commit_sha");
CREATE INDEX "IDX_action_run_job_pickup" ON "action_run_job" ("task_id","status","updated");
CREATE INDEX "IDX_action_run_job_status" ON "action_run_job" ("status");
CREATE INDEX "IDX_action_run_job_run_attempt_id" ON "action_run_job" ("run_attempt_id");
CREATE INDEX "IDX_action_run_job_is_reusable_caller" ON "action_run_job" ("is_reusable_caller");
CREATE INDEX "IDX_action_run_job_run_id" ON "action_run_job" ("run_id");
CREATE INDEX "IDX_action_run_job_repo_status" ON "action_run_job" ("repo_id","status");
CREATE INDEX "IDX_action_run_job_owner_id" ON "action_run_job" ("owner_id");
CREATE INDEX "IDX_action_run_job_attempt_job_id" ON "action_run_job" ("attempt_job_id");
SELECT setval('action_run_job_id_seq', COALESCE((SELECT MAX(id) + 1 FROM "action_run_job"), 1), false);

CREATE TABLE IF NOT EXISTS "gitea"."action_run_attempt_job_id_index" ("group_id" BIGINT PRIMARY KEY NOT NULL, "max_index" BIGINT NULL); ;
CREATE INDEX "IDX_action_run_attempt_job_id_index_max_index" ON "action_run_attempt_job_id_index" ("max_index");

CREATE TABLE IF NOT EXISTS "gitea"."action_run_job_summary" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "repo_id" BIGINT NULL, "run_id" BIGINT NULL, "run_attempt_id" BIGINT DEFAULT 0 NOT NULL, "job_id" BIGINT NULL, "step_index" BIGINT NULL, "content" TEXT NULL, "content_type" VARCHAR(255) DEFAULT 'text/markdown' NOT NULL, "content_size" BIGINT DEFAULT 0 NOT NULL, "created" BIGINT NULL, "updated" BIGINT NULL); ;
CREATE UNIQUE INDEX "UQE_action_run_job_summary_summary_key" ON "action_run_job_summary" ("repo_id","run_id","run_attempt_id","job_id","step_index");
SELECT setval('action_run_job_summary_id_seq', COALESCE((SELECT MAX(id) + 1 FROM "action_run_job_summary"), 1), false);

CREATE TABLE IF NOT EXISTS "gitea"."action_runner" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "uuid" CHAR(36) NULL, "name" VARCHAR(255) NULL, "version" VARCHAR(64) NULL, "owner_id" BIGINT NULL, "repo_id" BIGINT NULL, "description" TEXT NULL, "base" INTEGER NULL, "repo_range" VARCHAR(255) NULL, "token_hash" VARCHAR(255) NULL, "token_salt" VARCHAR(255) NULL, "last_online" BIGINT NULL, "last_active" BIGINT NULL, "agent_labels" TEXT NULL, "ephemeral" BOOL DEFAULT false NOT NULL, "is_disabled" BOOL DEFAULT false NOT NULL, "has_cancelling_support" BOOL DEFAULT false NOT NULL, "created" BIGINT NULL, "updated" BIGINT NULL, "deleted" BIGINT NULL); ;
CREATE UNIQUE INDEX "UQE_action_runner_uuid" ON "action_runner" ("uuid");
CREATE INDEX "IDX_action_runner_owner_id" ON "action_runner" ("owner_id");
CREATE INDEX "IDX_action_runner_repo_id" ON "action_runner" ("repo_id");
CREATE UNIQUE INDEX "UQE_action_runner_token_hash" ON "action_runner" ("token_hash");
CREATE INDEX "IDX_action_runner_last_online" ON "action_runner" ("last_online");
CREATE INDEX "IDX_action_runner_last_active" ON "action_runner" ("last_active");
SELECT setval('action_runner_id_seq', COALESCE((SELECT MAX(id) + 1 FROM "action_runner"), 1), false);

CREATE TABLE IF NOT EXISTS "gitea"."action_runner_token" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "token" VARCHAR(255) NULL, "owner_id" BIGINT NULL, "repo_id" BIGINT NULL, "is_active" BOOL NULL, "created" BIGINT NULL, "updated" BIGINT NULL, "deleted" BIGINT NULL); ;
CREATE UNIQUE INDEX "UQE_action_runner_token_token" ON "action_runner_token" ("token");
CREATE INDEX "IDX_action_runner_token_owner_id" ON "action_runner_token" ("owner_id");
CREATE INDEX "IDX_action_runner_token_repo_id" ON "action_runner_token" ("repo_id");
SELECT setval('action_runner_token_id_seq', COALESCE((SELECT MAX(id) + 1 FROM "action_runner_token"), 1), false);

CREATE TABLE IF NOT EXISTS "gitea"."action_schedule" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "title" VARCHAR(255) NULL, "specs" TEXT NULL, "repo_id" BIGINT NULL, "owner_id" BIGINT NULL, "workflow_id" VARCHAR(255) NULL, "trigger_user_id" BIGINT NULL, "ref" VARCHAR(255) NULL, "commit_sha" VARCHAR(255) NULL, "event" VARCHAR(255) NULL, "event_payload" TEXT NULL, "content" BYTEA NULL, "created" BIGINT NULL, "updated" BIGINT NULL); ;
CREATE INDEX "IDX_action_schedule_repo_id" ON "action_schedule" ("repo_id");
CREATE INDEX "IDX_action_schedule_owner_id" ON "action_schedule" ("owner_id");
SELECT setval('action_schedule_id_seq', COALESCE((SELECT MAX(id) + 1 FROM "action_schedule"), 1), false);

CREATE TABLE IF NOT EXISTS "gitea"."action_schedule_spec" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "repo_id" BIGINT NULL, "schedule_id" BIGINT NULL, "next" BIGINT NULL, "prev" BIGINT NULL, "spec" VARCHAR(255) NULL, "created" BIGINT NULL, "updated" BIGINT NULL); ;
CREATE INDEX "IDX_action_schedule_spec_repo_id" ON "action_schedule_spec" ("repo_id");
CREATE INDEX "IDX_action_schedule_spec_schedule_id" ON "action_schedule_spec" ("schedule_id");
CREATE INDEX "IDX_action_schedule_spec_next" ON "action_schedule_spec" ("next");
SELECT setval('action_schedule_spec_id_seq', COALESCE((SELECT MAX(id) + 1 FROM "action_schedule_spec"), 1), false);

CREATE TABLE IF NOT EXISTS "gitea"."action_scoped_workflow_source" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "owner_id" BIGINT DEFAULT 0 NOT NULL, "source_repo_id" BIGINT DEFAULT 0 NOT NULL, "workflow_configs" TEXT NULL, "created_unix" BIGINT NULL, "updated_unix" BIGINT NULL); ;
CREATE INDEX "IDX_action_scoped_workflow_source_source_repo_id" ON "action_scoped_workflow_source" ("source_repo_id");
CREATE UNIQUE INDEX "UQE_action_scoped_workflow_source_owner_repo" ON "action_scoped_workflow_source" ("owner_id","source_repo_id");
SELECT setval('action_scoped_workflow_source_id_seq', COALESCE((SELECT MAX(id) + 1 FROM "action_scoped_workflow_source"), 1), false);

CREATE TABLE IF NOT EXISTS "gitea"."action_task" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "job_id" BIGINT NULL, "attempt" BIGINT NULL, "runner_id" BIGINT NULL, "status" INTEGER NULL, "started" BIGINT NULL, "stopped" BIGINT NULL, "repo_id" BIGINT NULL, "owner_id" BIGINT NULL, "commit_sha" VARCHAR(255) NULL, "is_fork_pull_request" BOOL NULL, "token_hash" VARCHAR(255) NULL, "token_salt" VARCHAR(255) NULL, "token_last_eight" VARCHAR(255) NULL, "log_filename" VARCHAR(255) NULL, "log_in_storage" BOOL NULL, "log_length" BIGINT NULL, "log_size" BIGINT NULL, "log_indexes" BYTEA NULL, "log_expired" BOOL NULL, "created" BIGINT NULL, "updated" BIGINT NULL); ;
CREATE INDEX "IDX_action_task_runner_id" ON "action_task" ("runner_id");
CREATE INDEX "IDX_action_task_started" ON "action_task" ("started");
CREATE INDEX "IDX_action_task_commit_sha" ON "action_task" ("commit_sha");
CREATE UNIQUE INDEX "UQE_action_task_token_hash" ON "action_task" ("token_hash");
CREATE INDEX "IDX_action_task_token_last_eight" ON "action_task" ("token_last_eight");
CREATE INDEX "IDX_action_task_updated" ON "action_task" ("updated");
CREATE INDEX "IDX_action_task_status" ON "action_task" ("status");
CREATE INDEX "IDX_action_task_stopped_log_expired" ON "action_task" ("stopped","log_expired");
CREATE INDEX "IDX_action_task_repo_id" ON "action_task" ("repo_id");
CREATE INDEX "IDX_action_task_owner_id" ON "action_task" ("owner_id");
SELECT setval('action_task_id_seq', COALESCE((SELECT MAX(id) + 1 FROM "action_task"), 1), false);

CREATE TABLE IF NOT EXISTS "gitea"."action_task_output" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "task_id" BIGINT NULL, "output_key" VARCHAR(255) NULL, "output_value" TEXT NULL); ;
CREATE UNIQUE INDEX "UQE_action_task_output_task_id_output_key" ON "action_task_output" ("task_id","output_key");
CREATE INDEX "IDX_action_task_output_task_id" ON "action_task_output" ("task_id");
SELECT setval('action_task_output_id_seq', COALESCE((SELECT MAX(id) + 1 FROM "action_task_output"), 1), false);

CREATE TABLE IF NOT EXISTS "gitea"."action_task_step" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "name" VARCHAR(255) NULL, "task_id" BIGINT NULL, "index" BIGINT NULL, "repo_id" BIGINT NULL, "status" INTEGER NULL, "log_index" BIGINT NULL, "log_length" BIGINT NULL, "started" BIGINT NULL, "stopped" BIGINT NULL, "created" BIGINT NULL, "updated" BIGINT NULL); ;
CREATE INDEX "IDX_action_task_step_index" ON "action_task_step" ("index");
CREATE INDEX "IDX_action_task_step_repo_id" ON "action_task_step" ("repo_id");
CREATE INDEX "IDX_action_task_step_status" ON "action_task_step" ("status");
CREATE UNIQUE INDEX "UQE_action_task_step_task_index" ON "action_task_step" ("task_id","index");
CREATE INDEX "IDX_action_task_step_task_id" ON "action_task_step" ("task_id");
SELECT setval('action_task_step_id_seq', COALESCE((SELECT MAX(id) + 1 FROM "action_task_step"), 1), false);

CREATE TABLE IF NOT EXISTS "gitea"."action_tasks_version" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "owner_id" BIGINT NULL, "repo_id" BIGINT NULL, "version" BIGINT NULL, "created_unix" BIGINT NULL, "updated_unix" BIGINT NULL); ;
CREATE UNIQUE INDEX "UQE_action_tasks_version_owner_repo" ON "action_tasks_version" ("owner_id","repo_id");
CREATE INDEX "IDX_action_tasks_version_repo_id" ON "action_tasks_version" ("repo_id");
SELECT setval('action_tasks_version_id_seq', COALESCE((SELECT MAX(id) + 1 FROM "action_tasks_version"), 1), false);

CREATE TABLE IF NOT EXISTS "gitea"."action_variable" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "owner_id" BIGINT NULL, "repo_id" BIGINT NULL, "name" VARCHAR(255) NOT NULL, "data" TEXT NOT NULL, "description" TEXT NULL, "created_unix" BIGINT NOT NULL, "updated_unix" BIGINT NULL); ;
CREATE INDEX "IDX_action_variable_repo_id" ON "action_variable" ("repo_id");
CREATE UNIQUE INDEX "UQE_action_variable_owner_repo_name" ON "action_variable" ("owner_id","repo_id","name");
SELECT setval('action_variable_id_seq', COALESCE((SELECT MAX(id) + 1 FROM "action_variable"), 1), false);

CREATE TABLE IF NOT EXISTS "gitea"."task" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "doer_id" BIGINT NULL, "owner_id" BIGINT NULL, "repo_id" BIGINT NULL, "type" INTEGER NULL, "status" INTEGER NULL, "start_time" BIGINT NULL, "end_time" BIGINT NULL, "payload_content" TEXT NULL, "message" TEXT NULL, "created" BIGINT NULL); ;
CREATE INDEX "IDX_task_status" ON "task" ("status");
CREATE INDEX "IDX_task_doer_id" ON "task" ("doer_id");
CREATE INDEX "IDX_task_owner_id" ON "task" ("owner_id");
CREATE INDEX "IDX_task_repo_id" ON "task" ("repo_id");
SELECT setval('task_id_seq', COALESCE((SELECT MAX(id) + 1 FROM "task"), 1), false);

CREATE TABLE IF NOT EXISTS "gitea"."gpg_key" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "owner_id" BIGINT NOT NULL, "key_id" CHAR(16) NOT NULL, "primary_key_id" CHAR(16) NULL, "content" TEXT NOT NULL, "created_unix" BIGINT NULL, "expired_unix" BIGINT NULL, "added_unix" BIGINT NULL, "emails" TEXT NULL, "verified" BOOL DEFAULT false NOT NULL, "can_sign" BOOL NULL, "can_encrypt_comms" BOOL NULL, "can_encrypt_storage" BOOL NULL, "can_certify" BOOL NULL); ;
CREATE INDEX "IDX_gpg_key_owner_id" ON "gpg_key" ("owner_id");
CREATE INDEX "IDX_gpg_key_key_id" ON "gpg_key" ("key_id");
SELECT setval('gpg_key_id_seq', COALESCE((SELECT MAX(id) + 1 FROM "gpg_key"), 1), false);

CREATE TABLE IF NOT EXISTS "gitea"."gpg_key_import" ("key_id" CHAR(16) PRIMARY KEY NOT NULL, "content" TEXT NOT NULL); ;

CREATE TABLE IF NOT EXISTS "gitea"."public_key" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "owner_id" BIGINT NOT NULL, "name" VARCHAR(255) NOT NULL, "fingerprint" VARCHAR(255) NOT NULL, "content" TEXT NOT NULL, "mode" INTEGER DEFAULT 2 NOT NULL, "type" INTEGER DEFAULT 1 NOT NULL, "login_source_id" BIGINT DEFAULT 0 NOT NULL, "created_unix" BIGINT NULL, "updated_unix" BIGINT NULL, "verified" BOOL DEFAULT false NOT NULL); ;
CREATE INDEX "IDX_public_key_owner_id" ON "public_key" ("owner_id");
CREATE INDEX "IDX_public_key_fingerprint" ON "public_key" ("fingerprint");
SELECT setval('public_key_id_seq', COALESCE((SELECT MAX(id) + 1 FROM "public_key"), 1), false);

CREATE TABLE IF NOT EXISTS "gitea"."deploy_key" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "key_id" BIGINT NULL, "repo_id" BIGINT NULL, "name" VARCHAR(255) NULL, "key_type" INTEGER DEFAULT 1 NOT NULL, "fingerprint" VARCHAR(255) NULL, "token_hash" VARCHAR(255) NULL, "mode" INTEGER DEFAULT 1 NOT NULL, "created_unix" BIGINT NULL, "updated_unix" BIGINT NULL); ;
CREATE INDEX "IDX_deploy_key_token_hash" ON "deploy_key" ("token_hash");
CREATE INDEX "IDX_deploy_key_key_id" ON "deploy_key" ("key_id");
CREATE INDEX "IDX_deploy_key_repo_id" ON "deploy_key" ("repo_id");
SELECT setval('deploy_key_id_seq', COALESCE((SELECT MAX(id) + 1 FROM "deploy_key"), 1), false);

CREATE TABLE IF NOT EXISTS "gitea"."package" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "owner_id" BIGINT NOT NULL, "repo_id" BIGINT NULL, "type" VARCHAR(255) NOT NULL, "name" VARCHAR(255) NOT NULL, "lower_name" VARCHAR(255) NOT NULL, "semver_compatible" BOOL DEFAULT false NOT NULL, "is_internal" BOOL DEFAULT false NOT NULL); ;
CREATE UNIQUE INDEX "UQE_package_s" ON "package" ("owner_id","type","lower_name");
CREATE INDEX "IDX_package_owner_id" ON "package" ("owner_id");
CREATE INDEX "IDX_package_repo_id" ON "package" ("repo_id");
CREATE INDEX "IDX_package_type" ON "package" ("type");
CREATE INDEX "IDX_package_lower_name" ON "package" ("lower_name");
SELECT setval('package_id_seq', COALESCE((SELECT MAX(id) + 1 FROM "package"), 1), false);

CREATE TABLE IF NOT EXISTS "gitea"."package_blob" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "size" BIGINT DEFAULT 0 NOT NULL, "hash_md5" CHAR(32) NOT NULL, "hash_sha1" CHAR(40) NOT NULL, "hash_sha256" CHAR(64) NOT NULL, "hash_sha512" CHAR(128) NOT NULL, "created_unix" BIGINT NOT NULL); ;
CREATE UNIQUE INDEX "UQE_package_blob_md5" ON "package_blob" ("hash_md5");
CREATE INDEX "IDX_package_blob_hash_md5" ON "package_blob" ("hash_md5");
CREATE UNIQUE INDEX "UQE_package_blob_sha256" ON "package_blob" ("hash_sha256");
CREATE UNIQUE INDEX "UQE_package_blob_sha512" ON "package_blob" ("hash_sha512");
CREATE INDEX "IDX_package_blob_hash_sha1" ON "package_blob" ("hash_sha1");
CREATE UNIQUE INDEX "UQE_package_blob_sha1" ON "package_blob" ("hash_sha1");
CREATE INDEX "IDX_package_blob_hash_sha256" ON "package_blob" ("hash_sha256");
CREATE INDEX "IDX_package_blob_hash_sha512" ON "package_blob" ("hash_sha512");
CREATE INDEX "IDX_package_blob_created_unix" ON "package_blob" ("created_unix");
SELECT setval('package_blob_id_seq', COALESCE((SELECT MAX(id) + 1 FROM "package_blob"), 1), false);

CREATE TABLE IF NOT EXISTS "gitea"."package_blob_upload" ("id" VARCHAR(255) PRIMARY KEY NOT NULL, "bytes_received" BIGINT DEFAULT 0 NOT NULL, "hash_state_bytes" BYTEA NULL, "created_unix" BIGINT NOT NULL, "updated_unix" BIGINT NOT NULL); ;
CREATE INDEX "IDX_package_blob_upload_updated_unix" ON "package_blob_upload" ("updated_unix");

CREATE TABLE IF NOT EXISTS "gitea"."package_cleanup_rule" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "enabled" BOOL DEFAULT false NOT NULL, "owner_id" BIGINT DEFAULT 0 NOT NULL, "type" VARCHAR(255) NOT NULL, "keep_count" INTEGER DEFAULT 0 NOT NULL, "keep_pattern" VARCHAR(255) DEFAULT '' NOT NULL, "remove_days" INTEGER DEFAULT 0 NOT NULL, "remove_pattern" VARCHAR(255) DEFAULT '' NOT NULL, "match_full_name" BOOL DEFAULT false NOT NULL, "created_unix" BIGINT DEFAULT 0 NOT NULL, "updated_unix" BIGINT DEFAULT 0 NOT NULL); ;
CREATE UNIQUE INDEX "UQE_package_cleanup_rule_s" ON "package_cleanup_rule" ("owner_id","type");
CREATE INDEX "IDX_package_cleanup_rule_type" ON "package_cleanup_rule" ("type");
CREATE INDEX "IDX_package_cleanup_rule_enabled" ON "package_cleanup_rule" ("enabled");
CREATE INDEX "IDX_package_cleanup_rule_owner_id" ON "package_cleanup_rule" ("owner_id");
SELECT setval('package_cleanup_rule_id_seq', COALESCE((SELECT MAX(id) + 1 FROM "package_cleanup_rule"), 1), false);

CREATE TABLE IF NOT EXISTS "gitea"."package_file" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "version_id" BIGINT NOT NULL, "blob_id" BIGINT NOT NULL, "name" VARCHAR(255) NOT NULL, "lower_name" VARCHAR(255) NOT NULL, "composite_key" VARCHAR(255) NULL, "is_lead" BOOL DEFAULT false NOT NULL, "created_unix" BIGINT NOT NULL); ;
CREATE INDEX "IDX_package_file_composite_key" ON "package_file" ("composite_key");
CREATE INDEX "IDX_package_file_created_unix" ON "package_file" ("created_unix");
CREATE UNIQUE INDEX "UQE_package_file_s" ON "package_file" ("version_id","lower_name","composite_key");
CREATE INDEX "IDX_package_file_version_id" ON "package_file" ("version_id");
CREATE INDEX "IDX_package_file_blob_id" ON "package_file" ("blob_id");
CREATE INDEX "IDX_package_file_lower_name" ON "package_file" ("lower_name");
SELECT setval('package_file_id_seq', COALESCE((SELECT MAX(id) + 1 FROM "package_file"), 1), false);

CREATE TABLE IF NOT EXISTS "gitea"."package_property" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "ref_type" BIGINT NOT NULL, "ref_id" BIGINT NOT NULL, "name" VARCHAR(255) NOT NULL, "value" TEXT NOT NULL); ;
CREATE INDEX "IDX_package_property_ref_type" ON "package_property" ("ref_type");
CREATE INDEX "IDX_package_property_ref_id" ON "package_property" ("ref_id");
CREATE INDEX "IDX_package_property_name" ON "package_property" ("name");
SELECT setval('package_property_id_seq', COALESCE((SELECT MAX(id) + 1 FROM "package_property"), 1), false);

CREATE TABLE IF NOT EXISTS "gitea"."package_version" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "package_id" BIGINT NOT NULL, "creator_id" BIGINT DEFAULT 0 NOT NULL, "version" VARCHAR(255) NOT NULL, "lower_version" VARCHAR(255) NOT NULL, "created_unix" BIGINT NOT NULL, "is_internal" BOOL DEFAULT false NOT NULL, "metadata_json" TEXT NULL, "download_count" BIGINT DEFAULT 0 NOT NULL); ;
CREATE INDEX "IDX_package_version_package_id" ON "package_version" ("package_id");
CREATE INDEX "IDX_package_version_lower_version" ON "package_version" ("lower_version");
CREATE INDEX "IDX_package_version_created_unix" ON "package_version" ("created_unix");
CREATE INDEX "IDX_package_version_is_internal" ON "package_version" ("is_internal");
CREATE UNIQUE INDEX "UQE_package_version_s" ON "package_version" ("package_id","lower_version");
SELECT setval('package_version_id_seq', COALESCE((SELECT MAX(id) + 1 FROM "package_version"), 1), false);

CREATE TABLE IF NOT EXISTS "gitea"."access" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "user_id" BIGINT NULL, "repo_id" BIGINT NULL, "mode" INTEGER NULL); ;
CREATE UNIQUE INDEX "UQE_access_s" ON "access" ("user_id","repo_id");
SELECT setval('access_id_seq', COALESCE((SELECT MAX(id) + 1 FROM "access"), 1), false);

CREATE TABLE IF NOT EXISTS "gitea"."branch" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "repo_id" BIGINT NULL, "name" VARCHAR(255) NOT NULL, "commit_id" VARCHAR(255) NULL, "commit_message" TEXT NULL, "pusher_id" BIGINT NULL, "is_deleted" BOOL NULL, "deleted_by_id" BIGINT NULL, "deleted_unix" BIGINT NULL, "commit_time" BIGINT NULL, "created_unix" BIGINT NULL, "updated_unix" BIGINT NULL); ;
CREATE UNIQUE INDEX "UQE_branch_s" ON "branch" ("repo_id","name");
CREATE INDEX "IDX_branch_is_deleted" ON "branch" ("is_deleted");
CREATE INDEX "IDX_branch_deleted_unix" ON "branch" ("deleted_unix");
SELECT setval('branch_id_seq', COALESCE((SELECT MAX(id) + 1 FROM "branch"), 1), false);

CREATE TABLE IF NOT EXISTS "gitea"."renamed_branch" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "repo_id" BIGINT NOT NULL, "from" VARCHAR(255) NULL, "to" VARCHAR(255) NULL, "created_unix" BIGINT NULL); ;
CREATE INDEX "IDX_renamed_branch_repo_id" ON "renamed_branch" ("repo_id");
SELECT setval('renamed_branch_id_seq', COALESCE((SELECT MAX(id) + 1 FROM "renamed_branch"), 1), false);

CREATE TABLE IF NOT EXISTS "gitea"."commit_status" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "index" BIGINT NULL, "repo_id" BIGINT NULL, "state" VARCHAR(7) NOT NULL, "sha" VARCHAR(64) NOT NULL, "target_url" TEXT NULL, "description" TEXT NULL, "context_hash" VARCHAR(64) NULL, "context" TEXT NULL, "creator_id" BIGINT NULL, "created_unix" BIGINT NULL, "updated_unix" BIGINT NULL); ;
CREATE INDEX "IDX_commit_status_updated_unix" ON "commit_status" ("updated_unix");
CREATE UNIQUE INDEX "UQE_commit_status_repo_sha_index" ON "commit_status" ("index","repo_id","sha");
CREATE INDEX "IDX_commit_status_index" ON "commit_status" ("index");
CREATE INDEX "IDX_commit_status_repo_id" ON "commit_status" ("repo_id");
CREATE INDEX "IDX_commit_status_sha" ON "commit_status" ("sha");
CREATE INDEX "IDX_commit_status_context_hash" ON "commit_status" ("context_hash");
CREATE INDEX "IDX_commit_status_created_unix" ON "commit_status" ("created_unix");
SELECT setval('commit_status_id_seq', COALESCE((SELECT MAX(id) + 1 FROM "commit_status"), 1), false);

CREATE TABLE IF NOT EXISTS "gitea"."commit_status_index" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "repo_id" BIGINT NULL, "sha" VARCHAR(255) NULL, "max_index" BIGINT NULL); ;
CREATE UNIQUE INDEX "UQE_commit_status_index_repo_sha" ON "commit_status_index" ("repo_id","sha");
CREATE INDEX "IDX_commit_status_index_max_index" ON "commit_status_index" ("max_index");
SELECT setval('commit_status_index_id_seq', COALESCE((SELECT MAX(id) + 1 FROM "commit_status_index"), 1), false);

CREATE TABLE IF NOT EXISTS "gitea"."commit_status_summary" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "repo_id" BIGINT NULL, "sha" VARCHAR(64) NOT NULL, "state" VARCHAR(7) NOT NULL, "target_url" TEXT NULL); ;
CREATE UNIQUE INDEX "UQE_commit_status_summary_repo_id_sha" ON "commit_status_summary" ("repo_id","sha");
CREATE INDEX "IDX_commit_status_summary_repo_id" ON "commit_status_summary" ("repo_id");
CREATE INDEX "IDX_commit_status_summary_sha" ON "commit_status_summary" ("sha");
SELECT setval('commit_status_summary_id_seq', COALESCE((SELECT MAX(id) + 1 FROM "commit_status_summary"), 1), false);

CREATE TABLE IF NOT EXISTS "gitea"."lfs_meta_object" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "oid" VARCHAR(255) NOT NULL, "size" BIGINT NOT NULL, "repository_id" BIGINT NOT NULL, "created_unix" BIGINT NULL, "updated_unix" BIGINT NULL); ;
CREATE UNIQUE INDEX "UQE_lfs_meta_object_s" ON "lfs_meta_object" ("oid","repository_id");
CREATE INDEX "IDX_lfs_meta_object_oid" ON "lfs_meta_object" ("oid");
CREATE INDEX "IDX_lfs_meta_object_repository_id" ON "lfs_meta_object" ("repository_id");
CREATE INDEX "IDX_lfs_meta_object_updated_unix" ON "lfs_meta_object" ("updated_unix");
SELECT setval('lfs_meta_object_id_seq', COALESCE((SELECT MAX(id) + 1 FROM "lfs_meta_object"), 1), false);

CREATE TABLE IF NOT EXISTS "gitea"."lfs_lock" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "repo_id" BIGINT NOT NULL, "owner_id" BIGINT NOT NULL, "path" TEXT NULL, "created" TIMESTAMP NULL); ;
CREATE INDEX "IDX_lfs_lock_repo_id" ON "lfs_lock" ("repo_id");
CREATE INDEX "IDX_lfs_lock_owner_id" ON "lfs_lock" ("owner_id");
SELECT setval('lfs_lock_id_seq', COALESCE((SELECT MAX(id) + 1 FROM "lfs_lock"), 1), false);

CREATE TABLE IF NOT EXISTS "gitea"."protected_branch" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "repo_id" BIGINT NULL, "branch_name" VARCHAR(255) NULL, "priority" BIGINT DEFAULT 0 NOT NULL, "can_push" BOOL DEFAULT false NOT NULL, "enable_whitelist" BOOL NULL, "whitelist_user_i_ds" TEXT NULL, "whitelist_team_i_ds" TEXT NULL, "enable_merge_whitelist" BOOL DEFAULT false NOT NULL, "whitelist_deploy_keys" BOOL DEFAULT false NOT NULL, "merge_whitelist_user_i_ds" TEXT NULL, "merge_whitelist_team_i_ds" TEXT NULL, "enable_bypass_allowlist" BOOL DEFAULT false NOT NULL, "bypass_allowlist_user_i_ds" TEXT NULL, "bypass_allowlist_team_i_ds" TEXT NULL, "can_force_push" BOOL DEFAULT false NOT NULL, "enable_force_push_allowlist" BOOL DEFAULT false NOT NULL, "force_push_allowlist_user_i_ds" TEXT NULL, "force_push_allowlist_team_i_ds" TEXT NULL, "force_push_allowlist_deploy_keys" BOOL DEFAULT false NOT NULL, "enable_status_check" BOOL DEFAULT false NOT NULL, "status_check_contexts" TEXT NULL, "enable_approvals_whitelist" BOOL DEFAULT false NOT NULL, "approvals_whitelist_user_i_ds" TEXT NULL, "approvals_whitelist_team_i_ds" TEXT NULL, "required_approvals" BIGINT DEFAULT 0 NOT NULL, "block_on_rejected_reviews" BOOL DEFAULT false NOT NULL, "block_on_official_review_requests" BOOL DEFAULT false NOT NULL, "block_on_codeowner_reviews" BOOL DEFAULT false NOT NULL, "block_on_outdated_branch" BOOL DEFAULT false NOT NULL, "dismiss_stale_approvals" BOOL DEFAULT false NOT NULL, "ignore_stale_approvals" BOOL DEFAULT false NOT NULL, "require_signed_commits" BOOL DEFAULT false NOT NULL, "protected_file_patterns" TEXT NULL, "unprotected_file_patterns" TEXT NULL, "block_admin_merge_override" BOOL DEFAULT false NOT NULL, "created_unix" BIGINT NULL, "updated_unix" BIGINT NULL); ;
CREATE UNIQUE INDEX "UQE_protected_branch_s" ON "protected_branch" ("repo_id","branch_name");
SELECT setval('protected_branch_id_seq', COALESCE((SELECT MAX(id) + 1 FROM "protected_branch"), 1), false);

CREATE TABLE IF NOT EXISTS "gitea"."protected_tag" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "repo_id" BIGINT NULL, "name_pattern" VARCHAR(255) NULL, "allowlist_user_i_ds" TEXT NULL, "allowlist_team_i_ds" TEXT NULL, "created_unix" BIGINT NULL, "updated_unix" BIGINT NULL); ;
SELECT setval('protected_tag_id_seq', COALESCE((SELECT MAX(id) + 1 FROM "protected_tag"), 1), false);

CREATE TABLE IF NOT EXISTS "gitea"."project_board" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "title" VARCHAR(255) NULL, "default" BOOL DEFAULT false NOT NULL, "sorting" INTEGER DEFAULT 0 NOT NULL, "color" VARCHAR(7) NULL, "project_id" BIGINT NOT NULL, "creator_id" BIGINT NOT NULL, "created_unix" BIGINT NULL, "updated_unix" BIGINT NULL); ;
CREATE INDEX "IDX_project_board_updated_unix" ON "project_board" ("updated_unix");
CREATE INDEX "IDX_project_board_project_id" ON "project_board" ("project_id");
CREATE INDEX "IDX_project_board_created_unix" ON "project_board" ("created_unix");
SELECT setval('project_board_id_seq', COALESCE((SELECT MAX(id) + 1 FROM "project_board"), 1), false);

CREATE TABLE IF NOT EXISTS "gitea"."project_issue" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "issue_id" BIGINT NULL, "project_id" BIGINT NULL, "project_board_id" BIGINT NULL, "sorting" BIGINT DEFAULT 0 NOT NULL); ;
CREATE INDEX "IDX_project_issue_project_id" ON "project_issue" ("project_id");
CREATE INDEX "IDX_project_issue_project_board_id" ON "project_issue" ("project_board_id");
CREATE INDEX "IDX_project_issue_issue_id" ON "project_issue" ("issue_id");
SELECT setval('project_issue_id_seq', COALESCE((SELECT MAX(id) + 1 FROM "project_issue"), 1), false);

CREATE TABLE IF NOT EXISTS "gitea"."project" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "title" VARCHAR(255) NOT NULL, "description" TEXT NULL, "owner_id" BIGINT NULL, "repo_id" BIGINT NULL, "creator_id" BIGINT NOT NULL, "is_closed" BOOL NULL, "board_type" BIGINT NULL, "card_type" BIGINT NULL, "type" BIGINT NULL, "created_unix" BIGINT NULL, "updated_unix" BIGINT NULL, "closed_date_unix" BIGINT NULL); ;
CREATE INDEX "IDX_project_updated_unix" ON "project" ("updated_unix");
CREATE INDEX "IDX_project_title" ON "project" ("title");
CREATE INDEX "IDX_project_owner_id" ON "project" ("owner_id");
CREATE INDEX "IDX_project_repo_id" ON "project" ("repo_id");
CREATE INDEX "IDX_project_is_closed" ON "project" ("is_closed");
CREATE INDEX "IDX_project_created_unix" ON "project" ("created_unix");
SELECT setval('project_id_seq', COALESCE((SELECT MAX(id) + 1 FROM "project"), 1), false);

CREATE TABLE IF NOT EXISTS "gitea"."pull_auto_merge" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "pull_id" BIGINT NULL, "doer_id" BIGINT NOT NULL, "merge_style" VARCHAR(30) NULL, "message" TEXT NULL, "delete_branch_after_merge" BOOL NULL, "created_unix" BIGINT NULL, "merged_commit_id" VARCHAR(64) NULL); ;
CREATE INDEX "IDX_pull_auto_merge_doer_id" ON "pull_auto_merge" ("doer_id");
CREATE UNIQUE INDEX "UQE_pull_auto_merge_pull_id" ON "pull_auto_merge" ("pull_id");
SELECT setval('pull_auto_merge_id_seq', COALESCE((SELECT MAX(id) + 1 FROM "pull_auto_merge"), 1), false);

CREATE TABLE IF NOT EXISTS "gitea"."review_state" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "user_id" BIGINT NOT NULL, "pull_id" BIGINT DEFAULT 0 NOT NULL, "commit_sha" VARCHAR(64) NOT NULL, "updated_files" TEXT NOT NULL, "updated_unix" BIGINT NULL); ;
CREATE UNIQUE INDEX "UQE_review_state_pull_commit_user" ON "review_state" ("user_id","pull_id","commit_sha");
CREATE INDEX "IDX_review_state_pull_id" ON "review_state" ("pull_id");
SELECT setval('review_state_id_seq', COALESCE((SELECT MAX(id) + 1 FROM "review_state"), 1), false);

CREATE TABLE IF NOT EXISTS "gitea"."issue_assignees" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "assignee_id" BIGINT NULL, "issue_id" BIGINT NULL); ;
CREATE INDEX "IDX_issue_assignees_assignee_id" ON "issue_assignees" ("assignee_id");
CREATE INDEX "IDX_issue_assignees_issue_id" ON "issue_assignees" ("issue_id");
SELECT setval('issue_assignees_id_seq', COALESCE((SELECT MAX(id) + 1 FROM "issue_assignees"), 1), false);

CREATE TABLE IF NOT EXISTS "gitea"."comment" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "type" INTEGER NULL, "poster_id" BIGINT NULL, "original_author" VARCHAR(255) NULL, "original_author_id" BIGINT NULL, "issue_id" BIGINT NULL, "label_id" BIGINT NULL, "old_project_id" BIGINT NULL, "project_id" BIGINT NULL, "old_milestone_id" BIGINT NULL, "milestone_id" BIGINT NULL, "time_id" BIGINT NULL, "assignee_id" BIGINT NULL, "removed_assignee" BOOL NULL, "assignee_team_id" BIGINT DEFAULT 0 NOT NULL, "resolve_doer_id" BIGINT NULL, "old_title" VARCHAR(255) NULL, "new_title" VARCHAR(255) NULL, "old_ref" VARCHAR(255) NULL, "new_ref" VARCHAR(255) NULL, "dependent_issue_id" BIGINT NULL, "commit_id" BIGINT NULL, "line" BIGINT NULL, "tree_path" VARCHAR(4000) NULL, "content" TEXT NULL, "content_version" INTEGER DEFAULT 0 NOT NULL, "patch" TEXT NULL, "created_unix" BIGINT NULL, "updated_unix" BIGINT NULL, "commit_sha" VARCHAR(64) NULL, "review_id" BIGINT NULL, "invalidated" BOOL NULL, "ref_repo_id" BIGINT NULL, "ref_issue_id" BIGINT NULL, "ref_comment_id" BIGINT NULL, "ref_action" SMALLINT NULL, "ref_is_pull" BOOL NULL, "comment_meta_data" TEXT NULL); ;
CREATE INDEX "IDX_comment_dependent_issue_id" ON "comment" ("dependent_issue_id");
CREATE INDEX "IDX_comment_updated_unix" ON "comment" ("updated_unix");
CREATE INDEX "IDX_comment_review_id" ON "comment" ("review_id");
CREATE INDEX "IDX_comment_created_unix" ON "comment" ("created_unix");
CREATE INDEX "IDX_comment_ref_repo_id" ON "comment" ("ref_repo_id");
CREATE INDEX "IDX_comment_ref_issue_id" ON "comment" ("ref_issue_id");
CREATE INDEX "IDX_comment_ref_comment_id" ON "comment" ("ref_comment_id");
CREATE INDEX "IDX_comment_type" ON "comment" ("type");
CREATE INDEX "IDX_comment_poster_id" ON "comment" ("poster_id");
CREATE INDEX "IDX_comment_issue_id" ON "comment" ("issue_id");
SELECT setval('comment_id_seq', COALESCE((SELECT MAX(id) + 1 FROM "comment"), 1), false);

CREATE TABLE IF NOT EXISTS "gitea"."issue_content_history" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "poster_id" BIGINT NULL, "issue_id" BIGINT NULL, "comment_id" BIGINT NULL, "edited_unix" BIGINT NULL, "content_text" TEXT NULL, "is_first_created" BOOL NULL, "is_deleted" BOOL NULL); ;
CREATE INDEX "IDX_issue_content_history_issue_id" ON "issue_content_history" ("issue_id");
CREATE INDEX "IDX_issue_content_history_comment_id" ON "issue_content_history" ("comment_id");
CREATE INDEX "IDX_issue_content_history_edited_unix" ON "issue_content_history" ("edited_unix");
SELECT setval('issue_content_history_id_seq', COALESCE((SELECT MAX(id) + 1 FROM "issue_content_history"), 1), false);

CREATE TABLE IF NOT EXISTS "gitea"."issue_dependency" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "user_id" BIGINT NOT NULL, "issue_id" BIGINT NOT NULL, "dependency_id" BIGINT NOT NULL, "created_unix" BIGINT NULL, "updated_unix" BIGINT NULL); ;
CREATE UNIQUE INDEX "UQE_issue_dependency_issue_dependency" ON "issue_dependency" ("issue_id","dependency_id");
SELECT setval('issue_dependency_id_seq', COALESCE((SELECT MAX(id) + 1 FROM "issue_dependency"), 1), false);

CREATE TABLE IF NOT EXISTS "gitea"."issue" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "repo_id" BIGINT NULL, "index" BIGINT NULL, "poster_id" BIGINT NULL, "original_author" VARCHAR(255) NULL, "original_author_id" BIGINT NULL, "name" VARCHAR(255) NULL, "content" TEXT NULL, "content_version" INTEGER DEFAULT 0 NOT NULL, "milestone_id" BIGINT NULL, "priority" INTEGER NULL, "is_closed" BOOL NULL, "is_pull" BOOL NULL, "num_comments" INTEGER NULL, "ref" VARCHAR(255) NULL, "deadline_unix" BIGINT NULL, "created_unix" BIGINT NULL, "updated_unix" BIGINT NULL, "closed_unix" BIGINT NULL, "is_locked" BOOL DEFAULT false NOT NULL, "time_estimate" BIGINT DEFAULT 0 NOT NULL); ;
CREATE INDEX "IDX_issue_is_closed" ON "issue" ("is_closed");
CREATE INDEX "IDX_issue_created_unix" ON "issue" ("created_unix");
CREATE INDEX "IDX_issue_closed_unix" ON "issue" ("closed_unix");
CREATE UNIQUE INDEX "UQE_issue_repo_index" ON "issue" ("repo_id","index");
CREATE INDEX "IDX_issue_repo_id" ON "issue" ("repo_id");
CREATE INDEX "IDX_issue_poster_id" ON "issue" ("poster_id");
CREATE INDEX "IDX_issue_original_author_id" ON "issue" ("original_author_id");
CREATE INDEX "IDX_issue_is_pull" ON "issue" ("is_pull");
CREATE INDEX "IDX_issue_deadline_unix" ON "issue" ("deadline_unix");
CREATE INDEX "IDX_issue_updated_unix" ON "issue" ("updated_unix");
CREATE INDEX "IDX_issue_milestone_id" ON "issue" ("milestone_id");
SELECT setval('issue_id_seq', COALESCE((SELECT MAX(id) + 1 FROM "issue"), 1), false);

CREATE TABLE IF NOT EXISTS "gitea"."issue_index" ("group_id" BIGINT PRIMARY KEY NOT NULL, "max_index" BIGINT NULL); ;
CREATE INDEX "IDX_issue_index_max_index" ON "issue_index" ("max_index");

CREATE TABLE IF NOT EXISTS "gitea"."issue_pin" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "repo_id" BIGINT NOT NULL, "issue_id" BIGINT NOT NULL, "is_pull" BOOL NOT NULL, "pin_order" INTEGER DEFAULT 0 NULL); ;
CREATE UNIQUE INDEX "UQE_issue_pin_s" ON "issue_pin" ("repo_id","issue_id");
SELECT setval('issue_pin_id_seq', COALESCE((SELECT MAX(id) + 1 FROM "issue_pin"), 1), false);

CREATE TABLE IF NOT EXISTS "gitea"."issue_user" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "uid" BIGINT NULL, "issue_id" BIGINT NULL, "is_read" BOOL NULL, "is_mentioned" BOOL NULL); ;
CREATE UNIQUE INDEX "UQE_issue_user_uid_to_issue" ON "issue_user" ("uid","issue_id");
CREATE INDEX "IDX_issue_user_uid" ON "issue_user" ("uid");
CREATE INDEX "IDX_issue_user_issue_id" ON "issue_user" ("issue_id");
SELECT setval('issue_user_id_seq', COALESCE((SELECT MAX(id) + 1 FROM "issue_user"), 1), false);

CREATE TABLE IF NOT EXISTS "gitea"."issue_watch" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "user_id" BIGINT NOT NULL, "issue_id" BIGINT NOT NULL, "is_watching" BOOL NOT NULL, "created_unix" BIGINT NOT NULL, "updated_unix" BIGINT NOT NULL); ;
CREATE UNIQUE INDEX "UQE_issue_watch_watch" ON "issue_watch" ("user_id","issue_id");
SELECT setval('issue_watch_id_seq', COALESCE((SELECT MAX(id) + 1 FROM "issue_watch"), 1), false);

CREATE TABLE IF NOT EXISTS "gitea"."label" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "repo_id" BIGINT NULL, "org_id" BIGINT NULL, "name" VARCHAR(255) NULL, "exclusive" BOOL NULL, "exclusive_order" INTEGER DEFAULT 0 NULL, "description" VARCHAR(255) NULL, "color" VARCHAR(7) NULL, "num_issues" INTEGER NULL, "num_closed_issues" INTEGER NULL, "created_unix" BIGINT NULL, "updated_unix" BIGINT NULL, "archived_unix" BIGINT DEFAULT NULL NULL); ;
CREATE INDEX "IDX_label_updated_unix" ON "label" ("updated_unix");
CREATE INDEX "IDX_label_repo_id" ON "label" ("repo_id");
CREATE INDEX "IDX_label_org_id" ON "label" ("org_id");
CREATE INDEX "IDX_label_created_unix" ON "label" ("created_unix");
SELECT setval('label_id_seq', COALESCE((SELECT MAX(id) + 1 FROM "label"), 1), false);

CREATE TABLE IF NOT EXISTS "gitea"."issue_label" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "issue_id" BIGINT NULL, "label_id" BIGINT NULL); ;
CREATE UNIQUE INDEX "UQE_issue_label_s" ON "issue_label" ("issue_id","label_id");
SELECT setval('issue_label_id_seq', COALESCE((SELECT MAX(id) + 1 FROM "issue_label"), 1), false);

CREATE TABLE IF NOT EXISTS "gitea"."milestone" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "repo_id" BIGINT NULL, "name" VARCHAR(255) NULL, "content" TEXT NULL, "is_closed" BOOL NULL, "num_issues" INTEGER NULL, "num_closed_issues" INTEGER NULL, "completeness" INTEGER NULL, "created_unix" BIGINT NULL, "updated_unix" BIGINT NULL, "deadline_unix" BIGINT NULL, "closed_date_unix" BIGINT NULL); ;
CREATE INDEX "IDX_milestone_repo_id" ON "milestone" ("repo_id");
CREATE INDEX "IDX_milestone_created_unix" ON "milestone" ("created_unix");
CREATE INDEX "IDX_milestone_updated_unix" ON "milestone" ("updated_unix");
SELECT setval('milestone_id_seq', COALESCE((SELECT MAX(id) + 1 FROM "milestone"), 1), false);

CREATE TABLE IF NOT EXISTS "gitea"."pull_request" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "type" INTEGER NULL, "status" INTEGER NULL, "conflicted_files" TEXT NULL, "commits_ahead" INTEGER NULL, "commits_behind" INTEGER NULL, "changed_protected_files" TEXT NULL, "issue_id" BIGINT NULL, "index" BIGINT NULL, "head_repo_id" BIGINT NULL, "base_repo_id" BIGINT NULL, "head_branch" VARCHAR(255) NULL, "base_branch" VARCHAR(255) NULL, "merge_base" VARCHAR(64) NULL, "allow_maintainer_edit" BOOL DEFAULT false NOT NULL, "has_merged" BOOL NULL, "merged_commit_id" VARCHAR(64) NULL, "merger_id" BIGINT NULL, "merged_unix" BIGINT NULL, "flow" INTEGER DEFAULT 0 NOT NULL); ;
CREATE INDEX "IDX_pull_request_base_repo_id" ON "pull_request" ("base_repo_id");
CREATE INDEX "IDX_pull_request_has_merged" ON "pull_request" ("has_merged");
CREATE INDEX "IDX_pull_request_merger_id" ON "pull_request" ("merger_id");
CREATE INDEX "IDX_pull_request_merged_unix" ON "pull_request" ("merged_unix");
CREATE INDEX "IDX_pull_request_issue_id" ON "pull_request" ("issue_id");
CREATE INDEX "IDX_pull_request_head_repo_id" ON "pull_request" ("head_repo_id");
SELECT setval('pull_request_id_seq', COALESCE((SELECT MAX(id) + 1 FROM "pull_request"), 1), false);

CREATE TABLE IF NOT EXISTS "gitea"."reaction" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "type" VARCHAR(255) NOT NULL, "issue_id" BIGINT NOT NULL, "comment_id" BIGINT NULL, "user_id" BIGINT NOT NULL, "original_author_id" BIGINT DEFAULT 0 NOT NULL, "original_author" VARCHAR(255) NULL, "created_unix" BIGINT NULL); ;
CREATE INDEX "IDX_reaction_user_id" ON "reaction" ("user_id");
CREATE INDEX "IDX_reaction_original_author_id" ON "reaction" ("original_author_id");
CREATE INDEX "IDX_reaction_original_author" ON "reaction" ("original_author");
CREATE INDEX "IDX_reaction_created_unix" ON "reaction" ("created_unix");
CREATE UNIQUE INDEX "UQE_reaction_s" ON "reaction" ("type","issue_id","comment_id","user_id","original_author_id","original_author");
CREATE INDEX "IDX_reaction_type" ON "reaction" ("type");
CREATE INDEX "IDX_reaction_issue_id" ON "reaction" ("issue_id");
CREATE INDEX "IDX_reaction_comment_id" ON "reaction" ("comment_id");
SELECT setval('reaction_id_seq', COALESCE((SELECT MAX(id) + 1 FROM "reaction"), 1), false);

CREATE TABLE IF NOT EXISTS "gitea"."review" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "type" INTEGER NULL, "reviewer_id" BIGINT NULL, "reviewer_team_id" BIGINT DEFAULT 0 NOT NULL, "original_author" VARCHAR(255) NULL, "original_author_id" BIGINT NULL, "issue_id" BIGINT NULL, "content" TEXT NULL, "official" BOOL DEFAULT false NOT NULL, "commit_id" VARCHAR(64) NULL, "stale" BOOL DEFAULT false NOT NULL, "dismissed" BOOL DEFAULT false NOT NULL, "created_unix" BIGINT NULL, "updated_unix" BIGINT NULL); ;
CREATE INDEX "IDX_review_reviewer_id" ON "review" ("reviewer_id");
CREATE INDEX "IDX_review_issue_id" ON "review" ("issue_id");
CREATE INDEX "IDX_review_created_unix" ON "review" ("created_unix");
CREATE INDEX "IDX_review_updated_unix" ON "review" ("updated_unix");
SELECT setval('review_id_seq', COALESCE((SELECT MAX(id) + 1 FROM "review"), 1), false);

CREATE TABLE IF NOT EXISTS "gitea"."stopwatch" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "issue_id" BIGINT NULL, "user_id" BIGINT NULL, "created_unix" BIGINT NULL); ;
CREATE INDEX "IDX_stopwatch_issue_id" ON "stopwatch" ("issue_id");
CREATE INDEX "IDX_stopwatch_user_id" ON "stopwatch" ("user_id");
SELECT setval('stopwatch_id_seq', COALESCE((SELECT MAX(id) + 1 FROM "stopwatch"), 1), false);

CREATE TABLE IF NOT EXISTS "gitea"."tracked_time" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "issue_id" BIGINT NULL, "user_id" BIGINT NULL, "created_unix" BIGINT NULL, "time" BIGINT NOT NULL, "deleted" BOOL DEFAULT false NOT NULL); ;
CREATE INDEX "IDX_tracked_time_issue_id" ON "tracked_time" ("issue_id");
CREATE INDEX "IDX_tracked_time_user_id" ON "tracked_time" ("user_id");
SELECT setval('tracked_time_id_seq', COALESCE((SELECT MAX(id) + 1 FROM "tracked_time"), 1), false);

CREATE TABLE IF NOT EXISTS "gitea"."hook_task" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "hook_id" BIGINT NULL, "uuid" VARCHAR(255) NULL, "payload_content" TEXT NULL, "payload_version" INTEGER DEFAULT 1 NULL, "event_type" VARCHAR(255) NULL, "is_delivered" BOOL NULL, "delivered" BIGINT NULL, "is_succeed" BOOL NULL, "request_content" TEXT NULL, "response_content" TEXT NULL); ;
CREATE INDEX "IDX_hook_task_hook_id" ON "hook_task" ("hook_id");
CREATE UNIQUE INDEX "UQE_hook_task_uuid" ON "hook_task" ("uuid");
SELECT setval('hook_task_id_seq', COALESCE((SELECT MAX(id) + 1 FROM "hook_task"), 1), false);

CREATE TABLE IF NOT EXISTS "gitea"."webhook" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "repo_id" BIGINT NULL, "owner_id" BIGINT NULL, "is_system_webhook" BOOL NULL, "url" TEXT NULL, "name" VARCHAR(255) DEFAULT '' NOT NULL, "http_method" VARCHAR(255) NULL, "content_type" INTEGER NULL, "secret" TEXT NULL, "events" TEXT NULL, "is_active" BOOL NULL, "type" VARCHAR(16) NULL, "meta" TEXT NULL, "last_status" INTEGER NULL, "header_authorization_encrypted" TEXT NULL, "created_unix" BIGINT NULL, "updated_unix" BIGINT NULL); ;
CREATE INDEX "IDX_webhook_repo_id" ON "webhook" ("repo_id");
CREATE INDEX "IDX_webhook_owner_id" ON "webhook" ("owner_id");
CREATE INDEX "IDX_webhook_is_active" ON "webhook" ("is_active");
CREATE INDEX "IDX_webhook_created_unix" ON "webhook" ("created_unix");
CREATE INDEX "IDX_webhook_updated_unix" ON "webhook" ("updated_unix");
SELECT setval('webhook_id_seq', COALESCE((SELECT MAX(id) + 1 FROM "webhook"), 1), false);

CREATE TABLE IF NOT EXISTS "gitea"."action" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "user_id" BIGINT NULL, "op_type" INTEGER NULL, "act_user_id" BIGINT NULL, "repo_id" BIGINT NULL, "comment_id" BIGINT NULL, "is_deleted" BOOL DEFAULT false NOT NULL, "ref_name" VARCHAR(255) NULL, "is_private" BOOL DEFAULT false NOT NULL, "content" TEXT NULL, "created_unix" BIGINT NULL); ;
CREATE INDEX "IDX_action_user_id" ON "action" ("user_id");
CREATE INDEX "IDX_action_comment_id" ON "action" ("comment_id");
CREATE INDEX "IDX_action_au_r_c_u_d" ON "action" ("act_user_id","repo_id","created_unix","user_id","is_deleted");
CREATE INDEX "IDX_action_r_u_d" ON "action" ("repo_id","user_id","is_deleted");
CREATE INDEX "IDX_action_c_u_d" ON "action" ("created_unix","user_id","is_deleted");
CREATE INDEX "IDX_action_c_u" ON "action" ("user_id","is_deleted","created_unix");
CREATE INDEX "IDX_action_au_c_u" ON "action" ("act_user_id","created_unix","user_id");
SELECT setval('action_id_seq', COALESCE((SELECT MAX(id) + 1 FROM "action"), 1), false);

CREATE TABLE IF NOT EXISTS "gitea"."notification" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "user_id" BIGINT NOT NULL, "repo_id" BIGINT NOT NULL, "status" SMALLINT NOT NULL, "source" SMALLINT NOT NULL, "issue_id" BIGINT NOT NULL, "commit_id" VARCHAR(255) NULL, "comment_id" BIGINT NULL, "updated_by" BIGINT NOT NULL, "created_unix" BIGINT NOT NULL, "updated_unix" BIGINT NOT NULL); ;
CREATE INDEX "IDX_notification_idx_notification_repo_id" ON "notification" ("repo_id");
CREATE INDEX "IDX_notification_idx_notification_status" ON "notification" ("status");
CREATE INDEX "IDX_notification_idx_notification_source" ON "notification" ("source");
CREATE INDEX "IDX_notification_idx_notification_issue_id" ON "notification" ("issue_id");
CREATE INDEX "IDX_notification_idx_notification_commit_id" ON "notification" ("commit_id");
CREATE INDEX "IDX_notification_idx_notification_updated_by" ON "notification" ("updated_by");
CREATE INDEX "IDX_notification_u_s_uu" ON "notification" ("user_id","status","updated_unix");
CREATE INDEX "IDX_notification_idx_notification_user_id" ON "notification" ("user_id");
SELECT setval('notification_id_seq', COALESCE((SELECT MAX(id) + 1 FROM "notification"), 1), false);

CREATE TABLE IF NOT EXISTS "gitea"."secret" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "owner_id" BIGINT NOT NULL, "repo_id" BIGINT DEFAULT 0 NOT NULL, "name" VARCHAR(255) NOT NULL, "data" TEXT NULL, "description" TEXT NULL, "created_unix" BIGINT NOT NULL); ;
CREATE INDEX "IDX_secret_repo_id" ON "secret" ("repo_id");
CREATE UNIQUE INDEX "UQE_secret_owner_repo_name" ON "secret" ("owner_id","repo_id","name");
CREATE INDEX "IDX_secret_owner_id" ON "secret" ("owner_id");
SELECT setval('secret_id_seq', COALESCE((SELECT MAX(id) + 1 FROM "secret"), 1), false);

CREATE TABLE IF NOT EXISTS "gitea"."version" ("id" BIGSERIAL PRIMARY KEY  NOT NULL, "version" BIGINT NULL); ;
INSERT INTO "version" ("id", "version") VALUES (1,356);
SELECT setval('version_id_seq', COALESCE((SELECT MAX(id) + 1 FROM "version"), 1), false);
